### ISSUE TITLE
After upgrade RiotX re-asks for verification but other device already trust it.

### ISSUE THREAD

**Issue by tuxayo** [vector-im/element-android#1348]
I just update from 0.18.1 => 0.19.0 via F-Droid.

When opening, RiotX asks for verification. I accept but Riot web (https://riot.im/app) doesn't prompts for it.

And I see that Riot web already trusts the device.

I'm not try to circumvent like by disconnecting the device to "preserve the sample".

**Comment by tuxayo** [comment]
One rageshake has been sent mentioning this issue from RiotX and another one from Riot Web.

**Comment by kittykat** [comment]
Hi, thank you for filing this issue.

I'm going to close this issue for now because we introduced better debug logging for verification this year which would make it much easier to debug and the codebase around verification has significantly changed on both apps since this issue has been filed. If you experience it again, please submit rageshakes from both apps and file a new issue so we can have a look at it. Thank you!
