### ISSUE TITLE
screen is blinking after trying select options of videocall on lock screen

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#1597]
Steps to reproduce:
1. phone have lock by gesture 
1. lock phone - screen off
1. get incoming video-call
1. see full screen "incoming call screen"
1. press green button for accept call
1. call success begin
1. press ... fore change settings of call
1. screen begin blink and I do not stop this. Stop call on other phone not help. Only reboot phone.

Video of blinking by url: https://rsprim.ru/_matrix/media/r0/download/rsprim.ru/WesEKWfOJNkVPliEfrMHOEVN
I was stop call from second phone for record video - so call on video was ended, but screen is blinking.

Reproduce - always. But In second test end of call stop blinking.

RiotX version 0.23.0-dev [40023001] (G-b3059)

**Comment by beercanchicken** [comment]
Resurrecting this because it may be the same bug affecting me.
Element 1.0.12 from the F-Droid store, running on Android 7.1.1.  Steps to reproduce:

1. Lock the Android device running aforementioned version of Element so a passcode is required
2. Have another user place a call to the account attached to the device
3. Answer the call with the green button
4. The lock screen and call screen begin to "fight" for the screen
5. In my case this can be terminated by asking the other person to end the call

**Comment by progserega** [comment]
This bug is still reproduced in element-android 1.1.9
