### ISSUE TITLE
If message is read, the notification on other device wont close GooglePlay version 1.0.0

### ISSUE THREAD

**Issue by Wandelstock** [vector-im/element-android#1822]
Normally when a message is read the notifications on other device are also set read. This doesn't work on the android version (the webversion does set the notification to seen)

**Comment by matrixes** [comment]
I can confirm the behaviour;

1: Be logged in on both Element Android and Element Web, none of them in focus
2: Ask someone to type a message to you, get notifications in both applications
3a: Open the chat in Element Android

Expected behaviour: The notifications gets dismissed in both Android and on the Web
Actual behaviour: The notifications gets dismissed in both Android and on the Web

3b: Open the chat in Element Web

Expected behaviour: The notifications gets dismissed in both Android and on the Web
Actual behaviour: The notifications only gets dismissed on the Web

**Comment by bmarty** [comment]
I think #1144 would fix that. @MatMaul do you confirm?

**Comment by MatMaul** [comment]
I don't think so on his own, bit it could be part of the solution.
On top of my change, we need to call `refreshNotificationDrawer` when a read marker event is received.
And if we want it to work at all time we need to also push this event through FCM.
