### ISSUE TITLE
Image is lost after failing to send, no retry option

### ISSUE THREAD

**Issue by piegamesde** [vector-im/element-android#1836]
# Steps to reproduce

1. Take an image and send it
2. Have bad internet so that sending fails
3. Long tap on the message

In contrast to text messages, there is no "retry" option, only a "delete" one.

# Environment

- Element version: `1.0.0 [40100000]`
- Matrix SDK Version: `0.0.1`
- Olm version: `3.1.2`
- Encryped room

**Comment by ouchadam** [comment]
there were improvements to this area just after the issue was created https://github.com/vector-im/element-android/pull/1889

| RETRY IMAGE |
| --- |
![image-retry](https://user-images.githubusercontent.com/1848238/143435746-59779df1-ad37-41f2-9eba-e2d194f3c1ed.png)


closing as the retry functionality now exists, please reopen if I've misunderstood!
