### ISSUE TITLE
Make it harder to accidentally call someone

### ISSUE THREAD

**Issue by clarfon** [vector-im/element-android#1869]
Every other app immediately starts a call when pressing the button. I can't count the number of times I've seen someone accidentally press the button and start a call.

We can do better here and show a confirmation before starting the call so that it's harder to accidentally start a call when you're messaging someone. Alternatively, the option can be under a three-dot menu to make it harder to do accidentally.

**Comment by TR-SLimey** [comment]
Good idea, but needs to be done right in order to not be annoying. People used to just tapping and calling will probably get frustrated with this. I think putting the call button within a 3-dot menu at the top of the chat room is a good idea, because it will get rid of the "quick action" feel and users then won't expect to call instantly but rather go though some steps. A confirmation can then also be added.

**Comment by clarfon** [comment]
Good point, updated the issue to clarify the goal is to make accidental calls harder, and there are multiple ways to accomplish this. :)

**Comment by 532910** [comment]
Call must be a one tap action!

**Comment by bmarty** [comment]
The call button are at the top of screen, so it is hard to tap on it accidentally. And as you said, every other app start call immediately. On Riot-Android there was a confirmation dialog, so I will add a setting to add the dialog for users who really want to.
