### ISSUE TITLE
Add option to change email notification settings

### ISSUE THREAD

**Issue by samuel-p** [vector-im/element-android#2243]
**Is your feature request related to a problem? Please describe.**
In Element Web / Desktop there is an option in the settings (Notifications -> Enable email notifications) and I didn't find this option in Element Android. (It's a bit frustrating to tell others that they have to use the Web/Desktop Version to change this.)

**Describe the solution you'd like**
It would be awesome to have this option in Element Android too.

**Describe alternatives you've considered**
I think the easiest way is to ad another Toggle in the Notifications section in the settings.

**Additional context**
Here is the option in Element Web / Desktop:

![Bildschirmfoto von 2020-09-15 22-23-43](https://user-images.githubusercontent.com/7959516/95682504-d42bf900-0be5-11eb-935e-d5bae981a5c7.png)

**Comment by waclaw66** [comment]
This is quite necessary functionality missing on Android, some users which estabilished their users on Android devices got email notification set on. Don't know how, but they use Element Andorid only and they are quite upset getting notifications every hour.

**Comment by bmarty** [comment]
Ok, let's implement this:
- [ ] Add a setting to enable/disable email notification for emails associated to the account
- [ ] Under settings/Notifications add a new section below the section "Notifications", named "Email notification".
- [ ] If there is no email, a list item show "To receive email with notification, please associate an email to your Matrix account". Clicking on this item oopen the screen Settings/General/Emails and Phone numbers.
- [ ] If there are emails, for each email, a list item with a checkbox, same wording than Element Web, showing the state of the pusher related to the email.
- [ ] In the debug screen Settings/Advanced settings/Notification target, add a way to delete a pusher manually. Sometimes, ghost pushers stay here, maybe due to an (old) bug on Synapse, which did not delete pusher when user sign out

**Comment by ouchadam** [comment]
Fixed in [1.2.3](https://github.com/vector-im/element-android/milestone/35])
