### ISSUE TITLE
Fdroid not updating when new releases are released in github

### ISSUE THREAD

**Issue by janos-szenfner** [vector-im/element-android#2362]
The Fdroid not updated by the latest build (1.0.1.0)

When a new release viewable on the github a new apk should be abailable at fdroid or at github.

**Comment by bmarty** [comment]
Yes, release 1.0.10 is coming on F-Droid, please be patient :)

**Comment by emorrp1** [comment]
@bmarty looks like [the 1.0.10 build](https://f-droid.org/wiki/page/im.vector.app/lastbuild_40100100) failed on lack of [olm-3.1.2.jar](https://jitpack.io/org/matrix/gitlab/matrix-org/olm/3.1.2/olm-3.1.2.jar) because only a .aar has been published, so I'm assuming it's not a transient error that will be self-fixed next build.

**Comment by janos-szenfner** [comment]
It looks like that this is not a closed ticket, please open it.

**Comment by emorrp1** [comment]
I was wrong, the issue was transient and the latest (re)build was successful (same link), just waiting for the next repo publish to make the tag visible.
