### ISSUE TITLE
The Fdroid not updated by the latest build (1.0.10)

### ISSUE THREAD

**Issue by janos-szenfner** [vector-im/element-android#2378]
The Fdroid not updated by the latest build (1.0.10)

When a new release viewable on the github a new apk should be available at fdroid or at github. When you release a new version please upload the apk to the assets. 

#2362 is closed, although the issue is existing.
Check out the comments

**Comment by emorrp1** [comment]
AFAIK, Element have never manually published a release apk. All the docs point to Play Store, where the releases are controlled, and F-Droid, which is more like Debian where the authors are not in control of the release schedule. It can often take about 4 days to be published, but in this case it has taken longer due to build issues on F-Droid's side, so this should be raised with them unless there's a genuine issue with the tag.

**Comment by bmarty** [comment]
We release the source code and tag the master branch, which trigger the build for F-Droid and the release to F-Droid.

This process can take several days.

Also @janos-szenfner please avoid opening several issues for the same pb :)

**Comment by michaelblyons** [comment]
You can see the last build time (and results&mdash;sometimes they fail) at https://f-droid.org/wiki/page/im.vector.app/lastbuild. Then there's a delay (usually under 48 hours) for my phone's F-Droid to notice the newly built version.
