### ISSUE TITLE
b

### ISSUE THREAD

**Issue by ghost** [vector-im/element-android#2434]
x

**Comment by notramo** [comment]
Please don't. If someone wants to set it up, then they can do it from settings.
**Users don't want to write 48 characters down. No other messaging app asks for it.** They will screenshot it, and if they lose their phones, they will lose their backup too.
I tried recommending it to several non-techie users, and registering in Element Android was definitely easier than on Web, because
- .well-known discovery at server selection
- not requiring passphrase

**This would be a FTUE killer.** It is hard even now to get them using Matrix. This would worsen even more.
If you want your chat partners to be less secure, but more comfortable (secure backup by the way, degrades the excellent security Megolm down to that of PGP), then educate them. It is easier to learn how encryption works than to
- get a piece of paper
- get a pen
- write 48 random characters down
- put the paper in a secure place

Stop, before arguing further. **Speaking is easy. Having action is more difficult.** Recommend Element Android to e.g. 4 new non-techie users, and recommend Web too to 4 new non-techie users (so you will invite 8 new users to Matrix). **I did it** (with more users, but 8 would be sufficient). **And I speak from experience.** (Best to use a non-matrix.org server, e.g. grin.hu - actual server address: matrix.grin.hu - to experience it even more) If the registration was easier on Web, **then** come back to this issue.

**Comment by anoadragon453** [comment]
b gone spam
