### ISSUE TITLE
at-room parsing is wrongly identifying messages

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-android#2541]
The push rules don't trigger for at-room notifications put together with other sentences (`at-room1` for example), but Android's parsing appears to do a simple contains check instead. This can cause irrelevant notifications.

**Comment by deepbluev7** [comment]
I think there are 2 way how this could be fixed in Element Android:

Either you need to also match the @room rule here: https://github.com/matrix-org/matrix-android-sdk2/blob/235d432dfc102e2af0cbe9828fdd6b61af3310e1/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/pushrules/rest/PushCondition.kt#L66 to apply the special word delimited matching.

Or always use the wordOnly matching for any rule not using a glob, see: https://github.com/matrix-org/matrix-android-sdk2/blob/235d432dfc102e2af0cbe9828fdd6b61af3310e1/matrix-sdk-android/src/main/java/org/matrix/android/sdk/api/pushrules/EventMatchCondition.kt#L57

The proper solution and if this is an actual bug may depend on how the discussion on https://github.com/matrix-org/matrix-doc/issues/2913 turns out.

**Comment by eeble** [comment]
This is still an issue for instance when someone replies to a message that had 'at-room' in it, notifications are still generated on Android.
