### ISSUE TITLE
Add Option to Hide Message Content in Notifications

### ISSUE THREAD

**Issue by myano** [vector-im/element-android#2702]
**Is your feature request related to a problem? Please describe.**
Other secure messaging apps offer the ability for notifications to *not* contain the message preview for encrypted chats. To help keep E2EE messages secured this would be ideal to prevent leaking of secure messages.

**Describe the solution you'd like**
I would like to see a notification where it says "channel/user: sent X-number of messages"

**Describe alternatives you've considered**
I've looked at other Android clients for Matrix.org and I have yet to find one that allows for this feature.

I tried searching for existing feature requests for this and I didn't see anything. My apologies if my searching missed it.

**Comment by bmarty** [comment]
This actually exists, but is an extra setting which can be enabled only if a PIN code is configured to the application.

So go to "Settings/Security & Privacy/Protect access", then you can enable PIN code protection, then disable "Show content in notification"

**Comment by SimonBrandner** [comment]
I would be great to extract this setting as a separate thing. I wouldn't give my phone away to someone who I don't trust so I don't use the pin setting in Element. But I often find myself showing someone something on my phone and I don't necessarily want them to see my notification's content

**Comment by bmarty** [comment]
Yes, I understand your use case, and it reminds me https://muzzleapp.com/

The reason it's under the PIN setting is because it is strange to hide notification content if you can freely open the app and read all the messages.

**Comment by myano** [comment]
@bmarty ah, thank you! I found it. This works for me. I don't need the issue open any longer unless there really is a use case for folks who want to hide their notification content without a PIN?

**Comment by bmarty** [comment]
OK, happy to help and to close issues :)

**Comment by RinTohsaka64** [comment]
I could have sworn that years ago (like 4 years ago) this function existed without the need for a PIN...

My main interest in revisiting this is now that's it's on the record that push notifications are snooped on by "big brother" as it were:

 - https://www.wired.com/story/apple-google-push-notification-surveillance/

**Comment by bmarty** [comment]
Just giving some inputs here:
- the push data (data going to Google Firebase servers) does not contain message data, it contains `roomId` and `eventId`.
- the notification displayed on the phone contains message data and this can be disabled by setting up a pin and change the setting `Show content in notification`, but I do not understand reading https://www.wired.com/story/apple-google-push-notification-surveillance/ that these data are then known by Google (and/or Firebase).
- User are free to fully disable notification for the session, and even for the account, from the notification settings, and in these cases Firebase will not know about the user activity.
- Users are forced to trust the system, since the messages will be at some point displayed on their screen.

**Comment by RinTohsaka64** [comment]
Sorry, I should have emphesizes that I am fully aware of where the setting is, but I could have sworn that you used to be able to disable showing content in notification without setting up a PIN. This is exactly the functionality I am looking for as I swear I actually did use it in the past on family's devices.

I cannot help but feel like me mandating that they use a PIN will just result in them not using Element altogether due to "additional hoop-jumping". I mean, a big part of the whole cross-signing was to make things much less "hoop-jumpy" for these types of users, was it not?
