### ISSUE TITLE
Allow viewing images from url previews in attachement viewer

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-android#2705]
**Is your feature request related to a problem? Please describe.**
When seeing an url preview which includes an image (potentially it's just a link to an image) then it would be helpful to be able to view the fullscreen version of that image in element instead of having to click through and open it in a browser.

**Comment by bmarty** [comment]
Yes, why not, but generally the image has not too much interest. And clicking on the image open the link for the moment which is, the expected behavior, at least on mobile.

Element Web opens the image in big, but I never use this functionality. Clicking on a link on Web and on mobile are not the same think, and for mobile I prefer to keep the current behavior.

I keep the issue open to let other users give their point of view

**Comment by bmarty** [comment]
Now I understand this part:

> it's just a link to an image

but the client cannot guess that.

**Comment by bmarty** [comment]
I see, thanks for the extra motivation :). I'll see if I can find a couple of minutes to implement that.

**Comment by lub** [comment]
> Element Web opens the image in big, but I never use this functionality. Clicking on a link on Web and on mobile are not the same think, and for mobile I prefer to keep the current behavior.

FWIW I also use this functionality to prevent having to visit a 3rd party website and was confused enough about the deviation from element-web to search for this issue :)

**Comment by bmarty** [comment]
Fixed in 1.0.17
