### ISSUE TITLE
Wrong language code zh_Hans and zh_Hant in fastlane

### ISSUE THREAD

**Issue by linsui** [vector-im/element-android#2752]
**Describe the bug**
Wrong language code zh_Hans and zh_Hant in fastlane

**To Reproduce**
1. Go to https://github.com/vector-im/element-android/tree/develop/fastlane/metadata/android

**Expected behavior**
Many other apps use `zh-CN` and `zh-TW`/`zh-HK` and it seems that `zh-Hans` and `zh-Hant` are [suppoeted officially](https://github.com/fastlane/fastlane/blob/633860a5aae0fa9c0b936797560efb24181b1bf7/fastlane_core/lib/fastlane_core/languages.rb#L14). But `zh_Hans` and `zh_Hant` are used in this repo. I thought that this is the reason the Chinese translation of the fastlane is not shown in F-Droid client.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung S6]
 - OS: [e.g. Android 6.0]

**Additional context**
 - App version and store [e.g. 1.0.0 - F-Droid]
 - Homeserver: [e.g. matrix.org]

**Comment by eighthave** [comment]
[Fastlane](https://github.com/fastlane/fastlane/blob/633860a5aae0fa9c0b936797560efb24181b1bf7/fastlane_core/lib/fastlane_core/languages.rb#L14) uses [BCP47](https://www.w3.org/International/articles/bcp47/) locale tags, which use a `-` as the separator rather than `_`.    There are a number of locales that use the `_` here.  Please rename those dirs to use `-`.

@linsui FYI https://gitlab.com/fdroid/issuebot/-/issues/33#note_522152297

**Comment by ara4n** [comment]
So the fix for this is just to rename `zh-Hans` and `zh-Hant` as `zh_Hans` and `zh_Hant` throughout?

**Comment by linsui** [comment]
Not only zh-Hans and zh-Hant but also nb-NO and pt-BR. Thanks!

**Comment by linsui** [comment]
I guess this is just forgotten.
