### ISSUE TITLE
message rendering ignores the ol start argument

### ISSUE THREAD

**Issue by tulir** [vector-im/element-android#289]

**Comment by bmarty** [comment]
This is a limitation of markwon library (see https://github.com/noties/Markwon)

**Comment by MazeChaZer** [comment]
This was very confusing for me when someone texted me beginning the message with a (German) date ("9. would be better...") and RiotX just displayed ("1. would be better").

**Comment by auscompgeek** [comment]
I got confused by this recently myself. Seeing a whole bunch of messages that just start with "1." is quite confusing when the numbers are supposed to, you know, increase.

keywords: numbered list

**Comment by r4dh4l** [comment]
Sorry for pushing but the problem described in https://github.com/vector-im/element-android/issues/2189#issue-711844869 still exists and causes misunderstandings and disputes. https://github.com/vector-im/element-android/issues/2189#issuecomment-765527058 mentioned that this issue here is the right one to report.

**Comment by ouchadam** [comment]
Going to centralise the issue to #4777
