### ISSUE TITLE
#+ button on lower right when looking at an empty space goes to an empty 'Explore rooms'

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-android#3327]

**Comment by bmarty** [comment]
Thanks, I can reproduce it.

**Comment by BillCarsonFr** [comment]
@niquewoodhouse Do you have some ideas / empty screen / CTA for when the summary API returns no results.
It can be because:

- No rooms in space yet
- No 'visible room' (you don't have access / not peekable)
- [Already covered] Your home server does not support spaces

If you are an admin we could add actions to create/add rooms

**Comment by niquewoodhouse** [comment]
> No 'visible room' (you don't have access / not peekable)

This would be just private rooms?

**Comment by bmarty** [comment]
In EA 1.1.8
