### ISSUE TITLE
Publish new version to F-droid

### ISSUE THREAD

**Issue by rakshazi** [vector-im/element-android#3343]
#### Describe the bug

F-droid has only 1.1.6 version, 1.1.7 is not published

Related to https://github.com/vector-im/element-android/issues/2747

#### To Reproduce
Check available versions of the Element on F-Droid

#### Expected behavior
F-droid contains updated app version

#### Screenshots
N/A

#### Smartphone (please complete the following information):
 N/A

#### Additional context
 - Store: F-droid

**Comment by kojid0** [comment]
1.1.6 is the latest release. 1.1.7 is a pre-release ("beta"). Pre-releases don't get published on f-droid.

**Comment by rakshazi** [comment]
Thanks for clarification!

**Comment by HarHarLinks** [comment]
It's tagged as release, not pre-release though....

**Comment by kojid0** [comment]
> It's tagged as release, not pre-release though....

Yes it is. Since today. The team made a pre-release over the weekend to let users test and report issues. Then they decided to publish this as a release today. Now it will be built by F-Droid and will arrive in the next days.

**Comment by HarHarLinks** [comment]
Is that how it works? I have no evidence otherwise. However I suggest element-android follow the release tagging style of element-web and most matrix-org repos of tagging RCs explicitly and keeping them to avoid confusion.

for the record: [app was submitted to fdroid 4 days ago (thursday?)](https://gitlab.com/fdroid/fdroiddata/-/commits/master/metadata/im.vector.app.yml)

**Comment by kojid0** [comment]
Interesting... In the discussion of your provided link, they say that beta releases will not get published on F-Droid.
Different tagging style would be nice indeed. Since this issue is closed, maybe create a new one and suggest it?
