### ISSUE TITLE
Opening the app via a notification, then pressing back causes the syncing screen to appear

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-android#336]
Currently quite annoying and a bit of a blocker to using Riot X.

## Steps to reproduce

- Open a conversation from a notification
- Press back
- See the sync loading screen with the Riot logo.

Instead it should just return to the home screen, but complete the sync and update messages in the background. The user should not be blocked from using the app until a sync is complete.

Video: https://streamable.com/dbt4s

**Comment by bmarty** [comment]
Yes, we have noticed that. It's because the HomeActivity is created after the RoomActivity, since you go directly to the RoomActivity when you click on a notification.
There is nothing we can do, but the latest optimization we have done on RiotX has dramatically reduced the time the loader is displayed.

**Comment by anoadragon453** [comment]
Is it significantly less painful, but still not nice. Is it possible to launch the HomeActivity in the background?

**Comment by bmarty** [comment]
I don't sync so, and the System may even destroy the HomeActivity to reduce the memory consumption.

**Comment by bmarty** [comment]
No solution for the moment, but room list is displayed faster now.
