### ISSUE TITLE
Send button does not show up half of the time

### ISSUE THREAD

**Issue by cschmatzler** [vector-im/element-android#3535]
#### Describe the bug
In the current pre-release with the disappearing "send' button that only shows up when the message field isn't empty, it oftentimes does not show up even when a message has been written. Then, the input field needs to be completely deleted and content re-added for it to appear.

#### To Reproduce
1. Type a message.
2. If unlucky, button stays hidden.

#### Expected behavior
Let me send a message.

#### Smartphone (please complete the following information):
 - Device: Galaxy Note 10+
 - OS: Android 11

#### Additional context
 - App version and store: 1.1.10 [40101102] (G-b2627)
 - Homeserver: irrelevant

**Comment by bmarty** [comment]
Thanks for reporting.

I can reproduce 100% time with this scenario:
- type one letter
- delete it and type a letter quickly

-> The send button is not shown.

This is due to the lag caused by the animation. I will fix.

Also a workaround to make the button appear again is going back to the room list (the draft will be saved) and open the room again.

**Comment by Destroyer** [comment]
can you push a version with this fix? really annoying bug
thank you

**Comment by cschmatzler** [comment]
Hey @bmarty, thanks for the quick follow-up! Going back to the list is indeed a workaround for now, thanks for suggesting that.
Looking forward to see a release with #3540 on the beta channel soon!

**Comment by bmarty** [comment]
Fixed in 1.1.11
