### ISSUE TITLE
Reorganise Advanced Notifications in to Global Notifications, Keywords and Mentions, Other

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-android#3646]
This issue is to re-organise `Account Settings > Notifications > Advanced Notifications` in to `Global Notifications`, `Keyword and Mentions` and `Other`

The only change in functionality is that rather than 3 options for `off`, `silent` ,`noisey` there will just be a checkbox for on/off states with the on meaning `noisey.

This shows the new grouping under the `Account Settings > Notifications`:
![image](https://user-images.githubusercontent.com/6135282/124799975-0720d480-df4d-11eb-86a9-e247362b5ccd.png)

Global Notifications
![image](https://user-images.githubusercontent.com/6135282/124801041-47cd1d80-df4e-11eb-9422-d495946d308d.png)

Mentions and Keywords
![image](https://user-images.githubusercontent.com/6135282/124801075-50bdef00-df4e-11eb-9947-87fb98bf09ea.png)

Other
![image](https://user-images.githubusercontent.com/6135282/124801118-603d3800-df4e-11eb-8364-cc8c011b8361.png)

**Comment by AnisTaluqdar** [comment]
What about if someone replies to me? It would be great if there have an option to notify reply text.

**Comment by matthijskooijman** [comment]
> The only change in functionality is that rather than 3 options for off, silent ,noisey there will just be a checkbox for on/off states with the on meaning `noisey.

What's the rationale for this change?

I was very much using these options, so I can get noisy notifications for one-on-one rooms and mentions, and silent notifications for other rooms (that typically have too much activity to be noisy, but I do want to get a notification on the screen for their activity). This configuration was also the default, not sure if that has also changed? I recall reading an issue where this was discussed as the preferred default configuration to not overload people with noisy notifications by default. I can't quite find it again, but it does suggest that I'm not the only one that wants to use silent notifications.

It seems you can still configure silent notifications through element web, but I'm slightly worried that if this setting is removed in the Android version intentionally, it will also get dropped from the web version.

What's also a bit weird now, is that the Element Android now allow configuring "silent" and "noisy" (and "call") notification profiles. It does make sense to have these, since even if Element Android does not allow configuring silent notifications, they can be configured (through push rules) from other clients, so Element Android must be able to handle silent notifications I guess. But without a way to configure a notification as "silent" or "noisy", I expect this will be confusing to users (which will not know which of these two will be used when they put a checkbox for some notification category).

Also, anyone that still has silent notifications configured will just see the checkbox, and might end up being confused why some notifications are silent and some are noisy, since both will just have a checkbox. AFAICS, if they uncheck and recheck the checkbox, things will change from silent to noisy, which is also quite unexpected (I would expect that unchecking and rechecking a checkbox would restore the same state as before).
