### ISSUE TITLE
Wrong navigation after login

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#3898]
### Steps to reproduce

- Login to an existing account
- Click on the banner to verify the session
- Click on "Use a Recovery Passphrase or Key

### What did you expect?

I should see the passphrase form first, which include an option to open the Recovery Key form.

### What happened?

Recovery Key form is displayed first and if I press back I see the passphrase form

### Your phone model

Samsung S9

### Operating system version

Android 10

### Application version and app store

1.2.0

### Have you submitted a rageshake?

No

**Comment by bmarty** [comment]
Not reproduced with every accounts...
Can be reproduce with @benoit0816:matrix.org if necessary

**Comment by ouchadam** [comment]
the flow occurs when we enter the no passphrase branch of https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/crypto/quads/SharedSecureStorageViewModel.kt#L108

which I assume happens when `SharedSecretStorageService.getDefaultKey` returns a `KeyInfo` with `hasPassphrase=false`

`handleBack` always assumes we've come from the passphrase step https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/crypto/quads/SharedSecureStorageViewModel.kt#L170

@bmarty if your account doesn't have a passphrase then this might be a simple case of updating the back flow to skip the passphrase if we don't have one

however if this account/device does have a passphrase then there's something else going on... :thinking:

**Comment by bmarty** [comment]
Thanks for your investigation.
I confirm your analysis using my account @benoit0816:matrix.org: it doesn't have a passphrase then this might be a simple case of updating the back flow to skip the passphrase if we don't have one

**Comment by bmarty** [comment]
Fixed in 1.3.2
