### ISSUE TITLE
The voice recording of has when the screen turns off and what was recording is erased

### ISSUE THREAD

**Issue by discapacidad5** [vector-im/element-android#4194]
### Steps to reproduce

1. Where do you start? What can you see? When you stepped on the record button and slid it so that it stays recorded without having your finger on the screen, and starts recording a long message if the screen turns off the recording clears 2. What do you click? I click on voice mic 

### Your phone model

Samsung s9

### Operating system version

Android 10.0

### Application version and app store

Element versión  1.3.1 olm versión 3.2.4

### Homeserver

Matrix.org

### Have you submitted a rageshake?

No

**Comment by discapacidad5** [comment]
Note to self: add FLAG_KEEP_SCREEN_ON while recording

**Comment by ouchadam** [comment]
fixed by https://github.com/vector-im/element-android/pull/4557, will be in the 1.3.9 release

**Comment by nothingmuch** [comment]
Thank you for fixing this!

Although not strictly related to the bug or the fix, there is a deeper underlying issue IMO, merely triggered by the screen blanks, which is that user input is discarded when this happens/happened. I came here to report this issue after trying to record the same message 4 times today...

FWIW Signal added some functionality to save partial recordings in recent versions, which is very helpful when there are other interruptions like a phone call that comes in while recording, and this has improved its usability for me dramatically.

Conversely I've stopped using wire and keybase mainly because of long standing bugs related to this (e.g. apparently compressing the audio in the UI thread, screen blanking bugs etc), because there are few things more frustrating to me than getting a question with a complicated answer, taking the time to record detailed response without really planning, and then having to do it all over again. It's very hard to compensate for these bugs and remember that all my thoughts will be lost just as I get into the zone if i don't wiggle my thumb or if i dare use the lock functionality.
