### ISSUE TITLE
Explore rooms doesn't make good use of space

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#4304]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

#### What did you expect?
Explore rooms shows me list of rooms in a space (ideally it also tells me what space I'm looking at)

I am not expecting to know how many members a space has from the explore rooms view

e.g.
![Screenshot_20211021-164325](https://user-images.githubusercontent.com/51663/138316925-358300de-2715-488d-aa00-320c080a4d3c.png)

#### What happened instead?
A large portion of the view is taken up with unused space and as a user, when I want to explore rooms, I'm not interested in the information about the space
![Screenshot_20211021-164325 (1)](https://user-images.githubusercontent.com/51663/138317299-c0b10032-ffcc-4c9b-acf1-60c580ad0a4e.png)

### Application version and app store

Element 1.3.4 (RC)

### Will you send logs?

No

**Comment by niquewoodhouse** [comment]
I think that's a good enough improvement to ship but, there are some things missing that would help people exploring:

- Search
- Labelling of 'subspaces'

**Comment by fedrunov** [comment]
There are some extra spaces where same layout/design is used 

When user tap on link invite to room
![room_invite](https://user-images.githubusercontent.com/66663241/152004843-767f93f2-e594-45a4-991b-2e1b099e959b.png)

when user tap on link invite to space
![space_invite](https://user-images.githubusercontent.com/66663241/152004854-cfa7a1c1-a91a-4689-a53f-e6d4f3b97476.png)

@niquewoodhouse do we want to update all of them at once, or only "explore room" screen?

I suggest change everywhere but leave description and "people you might now" section visible for invites.

**Comment by fedrunov** [comment]
@niquewoodhouse small problem:

member count group has background and on black theme it's not visible at "explore room" screen. Since there is padding for image, it breaks left alignment of views

| Invite | Explore | 
| - | - |
| ![invite](https://user-images.githubusercontent.com/66663241/152127210-de0e4425-5317-4940-b615-e98d9a8dc29e.png) | ![explore](https://user-images.githubusercontent.com/66663241/152127216-55a02a36-1e39-4a6d-beca-69b1c42a853d.png) |

There is no problem on light theme - background is always visible. 

I suggest we file this as a separate ticket with minor priority

**Comment by bmarty** [comment]
Will be in Element 1.3.18
