### ISSUE TITLE
Try compress video before send

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#442]
Users often try send big video to chat and it is success sending in other chats (such as whatspp, telegram), because other chats-clients repack video to small size on fly.
But not riot. Riot try send full video and often can not do that.

People be accustomed to this feature and want see it in RiotX.

**Comment by bmarty** [comment]
Also it may lead to #587

**Comment by Tesla2k** [comment]
This is absolutely needed. No normal person will switch from WhatsApp or whatever to Riot if this is not added. (It should be added to all Matrix clients)

**Comment by Jouski** [comment]
Yes it would be a great idea to add this feature as in XMPP client Conversations.

**Comment by Fuzzillogic** [comment]
A participant in a group chat sent a video from their phone. The video was 92MiB. The user was on matrix.org, while other group members, as well as  the group chat location, was on a self-hosted Synapse server. We could see the thumbnail, but trying to download or play the video resulted in nothing. While I still in the dark what this particular problem is (some room limits I'm not aware of?), it could have been avoided by recompressing the video to something much smaller, just like when sending photos. Most clips don't need the quality, and is wasteful when on mobile data bundles. The option to send the original is still welcome though; sometimes you do want the quality.

Also, VP9 WebM seems to work fine in Element. It would instantly improve compression rate over AVC, while maintaining quality. The same goes for using WebP instead of jpg and png. WebP also supports lossless, with compression much better than png.

**Comment by bmarty** [comment]
Implemented in 1.1.7 (#3264)

**Comment by r4dh4l** [comment]
@bmarty Thank you for implementing this feature but from my experience the compression has almost no effect to the original size. Is there any way to set the compression level to what Handbrake does with Preset "General -> Very Fast 720p30" (with "Web Pptimized" enabled)?

**Comment by jtrees** [comment]
I can confirm that the file size for compressed files is always the same as the input file after "compression" for all videos I've sent so far (about 10).

**Comment by vetko** [comment]
I can also confirm this, unfortunately: even when leaving the "Send video with the original size" _unchecked_, it does not change the size of videos (e.g. uploading a 200Mb video as 200Mb).  
Have tried with multiple videos, different devices. The uploads are to encrypted rooms.
