### ISSUE TITLE
Disable auto signout when a homeserver is unreachable

### ISSUE THREAD

**Issue by ThellraAK** [vector-im/element-android#4464]
#### What would you like to do?
For signouts due to a server timeout to not be automatic
#### Why would you like to do it?
Instead of signing out when it can't contact the server, maybe be like "server's down or doesn't like you, want to sign out and try again or something?"
#### How would you like to achieve it?
By asking here nicely

### Have you considered any alternatives?

This issue could be avoided and not an issue had I written down the backup phrase or saved keys somewhere.

### Additional context

Today I needed to migrate my homeserver and I messed up a bit, and it was down for an hour and a half instead of a few minutes, I had two clients open (android and Linux desktop) and they both signed themselves out during the downtime, another user who had their android app signed out, but didn't have their desktop client open, and was able to verify through there.  It would be nice if it didn't auto sign out when the server is down.

**Comment by bmarty** [comment]
Element Android does not sign out the session in case of homeserver's time out or if it cannot be reached, this is strange. I suspect that the homeserver was live at some point but returned invalid token or similar error, and so the client has destroyed the session.

**Comment by ouchadam** [comment]
from my understanding the homeserver needs to respond with a 401 **and** a custom json response with `M_UNKNOWN_TOKEN` in order to automatically sign the client out 

I do agree that this isn't a nice scenario and could ruin a lot of peoples day if they haven't backed up their accounts but it's also the same mechanism that protects devices when changing passwords/revoking sessions

do you know the steps which caused the homeserver to temporarily be in an invalid state? it might be something we can better document or perhaps uncover a bug within synapse causing eager token invalidations

**Comment by fedrunov** [comment]
Closed since additional information is needed but author didn't reply for a while
