### ISSUE TITLE
Element not working anymore on matrix.org with Android 7.0 (SSL error)

### ISSUE THREAD

**Issue by ipoupaille** [vector-im/element-android#4550]
### Steps to reproduce

Perhaps it is the same than https://github.com/vector-im/element-android/issues/4253

Matrix.org server do not send (anymore ?) cross signed ISRG ROOT X1 (by DST). So devices on android 7.0 (which do no authorize user certificats by default) can not anymore connect to this server.

### Outcome

2 solutions:
1/ Add ISRG Root X1 on network_security_config.xml in the trust certificats for the app
2/ Allow user certificats in network_security_config.xml

### Your phone model

Motorola X Force

### Operating system version

Android 7.0

### Application version and app store

PlayStore Element 1.3.7

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ouchadam** [comment]
thanks for raising! there's been a change to matrix.org's certificate, we're looking into moving to the default chain

will update once it's done

**Comment by ouchadam** [comment]
The certificate has been updated

@ipoupaille has this resolved your issue?

**Comment by ipoupaille** [comment]
The app is working again, thanks.
Will you still add ISRG Root X1 to your trusted certificats?

**Comment by ouchadam** [comment]
we don't currently have any plans to include the certificate directly in the application, this may change once the cross signed certificate expires in September 2024 and we still have a reasonable amount 7.0 and below users.

although... by then there will be a strong argument to drop support for those android versions due to security concerns (7.0 will be over 8 years old!)
