### ISSUE TITLE
Notifications experience is not the same when compared to the web / IOS client

### ISSUE THREAD

**Issue by alongls** [vector-im/element-android#4632]
### Steps to reproduce

1. Where are you starting? What can you see?
when testing the notifications when message is received we see that the android client behavior is different than the IOS or WEB client.
when several messages from the same person are received in IOS device we hear notification sound per message that is received (e.g. if received 5 messages from the same person we will hear 5 beeps) also the app indicator will show 5 to let us know that 5 messages are waiting for us
in the web client we will also hear sounds as per message that is received.
in the Android client it is not like that
the Android client will play one sound even if multiple message are received from the same person
the android client will show on the app icon that 1 message is waiting for us although there are multiple messages waiting
 
2. What do you click?
3. More steps…

#### What did you expect?

sound per received message even if messages are received from the same person / room (as in the IOS / WEC client and as in whatsapp)

#### What happened instead?

one sound although  several messages were received. number on icon was also wrong

### Your phone model

Samsung s21 (several model tested)

### Operating system version

android 7-10

### Application version and app store

element version 1.3.7 olm 3.2.4

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
I'm tempted to swap this to an enhancement, previously we've had reports of the notifications happening too often, especially in high traffic rooms

This feels like direct messages could have different behaviour to rooms or we allow the mobile clients to control `noisy` notifications cc @daniellekirkwood

**Comment by alongls** [comment]
Hello
what ever you decide to do you need to make sure that the behavior will be the same across all platforms.
you can not maintain 3 platforms (web. ios, android) that behave differently since t will confuse the users and will guide tham away from this solution.

**Comment by daniellekirkwood** [comment]
Great issue to raise - and great context added, thanks both. 

I agree with @ouchadam that this is an Enhancement for us, however I think you raise a great point @alongls and we should look at the solution holistically across platforms.

**Comment by alongls** [comment]
fully agree
this is why we moved away from the app until this issue will be resolved (if the team will decide to change the current behavior).

**Comment by binarydad** [comment]
Thanks for consolidating this.

**Comment by matrixes** [comment]
I miss a lot of conversations on specifically Android that I don't on either web or IOS, because of the way notifications behave on Android.

As others have stated, I agree the behaviour really needs to be consistent over the different platforms because as it is now, (as Android is the only client behaving like this and it being my daily driver), I have to double and triple check my phone to see if I've missed out on any conversation.

If there's any suggestion gathering from users at this point, I'd like to propose that

* all platforms behave the same (as their defaults)
* giving the end users more control of how they'd like to be notified is preffered
* to preserve consistency between platforms, even if users are able to affect settings much more granularly by themselves, the app could be set to the same behaviour as the other platforms by default on first install.

> I'm tempted to swap this to an enhancement, previously we've had reports of the notifications happening too often, especially in high traffic rooms

This makes me curious. Is it only/majority Android-users that experience that notifications happen too often? Considering that web and IOS get notified for each message (unless muted, of course), wouldn't that also result in the same type of reports from other platform users?
Or is this perhaps a result of a higher number of Android users?
Anyways, it was just something that stood out that I became curious of.

> This feels like direct messages could have different behaviour to rooms or we allow the mobile clients to control `noisy` notifications cc @daniellekirkwood

As a sidenote; I have also had a request up for being able to set individual sounds for individual rooms for Android since a few years back. It would give me freedom to, by sound, determine if I'd like to get involved in the discussions (https://github.com/vector-im/element-android/issues/534)

**Comment by giomfo** [comment]
@daniellekirkwood I would suggest notifying for each message on Android (when the notifications are enabled for the room) to adopt the same behavior as iOS and Web, until we rework/enhance the notifications handling

If you agree, we can prepare a PR for this change. Please let me know if you prefer keeping it like this

**Comment by daniellekirkwood** [comment]
Yes @giomfo, let's complete the work to make it consistent across platforms. Then we can work on improving it.

**Comment by alongls** [comment]
Great news
waiting for the app update.
thanks

**Comment by lindhe** [comment]
I believe [release v1.4.16](https://github.com/vector-im/element-android/releases/tag/v1.4.16) tried to reference this issue, but used the incorrect issue number.

> * Notify the user for each new message ([#46312](https://github.com/vector-im/element-android/issues/46312))

**Comment by binarydad** [comment]
FYI, it seems there is still an issue with older Android devices (ver 8 and older, IIRC) that are making TWO sounds for the first message received, and one for each one thereafter. 

I noticed the same behavior when I was messing with tackling this same issue. I'll submit a bug later when I get around to it unless someone else does first.

**Comment by Claire1817** [comment]
Thanks @binarydad for your feedback, can you create a new issue please ?
