### ISSUE TITLE
Remove Typing notification in the Room list

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-android#4760]
Let's remove the typing notification from the room list view on Android... 

It's distracting and can cause performance issues - it doesn't add a great deal of value so let's remove it!

Leave your thoughts in the comments...

**Comment by notramo** [comment]
Please don't remove it, as some users can find it useful. For example, I use it.
But if it causes performance issues, then put it behind a config option.
The setting should have 3 options:
- off
- on
- (default) on if less than 30 rooms in the list, otherwise off

**Comment by Flam3z** [comment]
If its still decided to be removed can it at least stay for DMs?

**Comment by notramo** [comment]
I think it doesn't matter performance-wise if it's a DM or group. If somebody has lot of DMs, then it will be slow.

**Comment by ouchadam** [comment]
I'm interested to hear about how people are using the room list and how the typing status fits into the picture.
Is it a feature people also miss on Web?

**Comment by notramo** [comment]
For example, if I'm on mobile data, and I want to switch it off to save bandwidth, but I notice that someone is typing, then wait for that message before going offline.

**Comment by Flam3z** [comment]
> I'm interested to hear about how people are using the room list and how the typing status fits into the picture. Is it a feature people also miss on Web?

From my memory I dont think that is a feature on web.

**Comment by AnisTaluqdar** [comment]
Can you try it? Instead of removing it.

![c25b8ece36f746f210e0d1b349975785c2559673.png](https://user-images.githubusercontent.com/41234183/147337461-674156c0-1aa1-4cd3-873a-feb26060ad92.png)

**Comment by ouchadam** [comment]
there might be a little bit of a misunderstanding here, this issue is for removing the typing status from the room list only

| DM | ROOM |
| --- | --- |
![Screenshot_20211224_091601](https://user-images.githubusercontent.com/1848238/147338978-45e1eb04-9b06-4144-9542-6e368c966458.png)|![Screenshot_20211224_091539](https://user-images.githubusercontent.com/1848238/147338980-7ab37ba3-2787-4691-b861-c69120487d4a.png)

**Comment by Flam3z** [comment]
If its very distracting for a majority of users has a redesign been considered?

**Comment by bmarty** [comment]
On my side I find it useful, especially when there are several active conversations, you can see that a new message is coming soon in one of them.

> cause performance issues

What makes you say that?

Rather than removing a feature which has no bug so far, it could be better to enhance it, for instance by adding more added value:
- "x is recording an audio message"
-  "x is replying to a thread"
- etc.

Also worth noting that the typing notification is also displayed in the breadcrumbs panel:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/3940906/147758247-e5ea9fb7-58c3-4552-98f9-783567506625.png">

Last point, it mimics WhatsApp behavior.

**Comment by ouchadam** [comment]
> cause performance issues

this was a comment from me and it stems from us observing more events than if we didn't show the typing status for all rooms, if there's no known performance impact then we can safely ignore that point

**Comment by daniellekirkwood** [comment]
Thanks everyone for the feedback!
