### ISSUE TITLE
Having hardcoded attributes (like colours) for assets makes maintenance hard for downstream forks

### ISSUE THREAD

**Issue by benparsons** [vector-im/element-android#4860]
#### Problem

We have users who maintain forks downstream of element-android. Sometimes they want to edit assets to match their own branding. Maintaining such a fork is hard when there are hard-coded attributes in assets.

#### Example

This value was changed: https://github.com/vector-im/element-android/blob/78bdef4e2d3f2eec67b67f93637052ee25881b3e/vector/src/main/res/drawable/ic_shield_trusted_no_border.xml#L8
By this PR: https://github.com/vector-im/element-android/pull/4338

This small change created significant work downstream, because it wasn't clear what had changed

#### Suggestion

Could these attribute values be stored centrally?

### Additional context

Internal issue ref: https://element-io.atlassian.net/browse/PSC-46

**Comment by chagai95** [comment]
Here's another example:
https://github.com/vector-im/element-web/issues/20413

**Comment by bmarty** [comment]
We can use the `accent` color for vector drawables, however in this particular case (the green shield), I'm not sure it is relevant.
Supposed that a fork want to change the accent color to `red`. The green shield will become a red shield and this is not what we are expecting.
What we can do is extract this specific color `#0DBD8B` to one or several variables (for instance `trust_shield_color` which can have the value `#0DBD8B` by default) so that they can be customized more easily on forks.

**Comment by bmarty** [comment]
Fixed in 1.4.6
