### ISSUE TITLE
Make submitting a report (rageshake) easier or similar to how it works on web

### ISSUE THREAD

**Issue by claell** [vector-im/element-android#4881]
#### What would you like to do?
I was prompted to share logs
#### Why would you like to do it?
I was prompted to do so
#### How would you like to achieve it?
Did not matter

### Have you considered any alternatives?

Yes, after being told to just shake my phone, I did that

### Additional context

On the web client, I could either send a report/logs through the help menu or with `/rageshake`. On Android, there was no such option in the help menu and also the command did not work. That is a bit unfortunate, as I was not aware that I just had to shake my phone.

**Comment by bmarty** [comment]
'/rageshake` does not exist on Element Android, it has less sense than on Element Web (you will not shake your computer), but note that you can also send rageshakes from the top right menu in the room list: "Report bug".

<img width="462" alt="image" src="https://user-images.githubusercontent.com/3940906/148608008-a1526876-258a-43b0-b8e6-032793472be3.png">

The advantage of shaking your phone is that you can do it on any screen of the app, so that we can get useful screenshot of the screen, if you opt-in to send it.

**Comment by kittykat** [comment]
@bmarty is there any downside to enabling the /rageshake command on mobile to provide a more consistent experience with web? I often find myself typing it out on autopilot and can't think of any downsides

**Comment by bmarty** [comment]
Ok, added in #12

**Comment by claell** [comment]
@bmarty Thanks! For an even more consistent experience with web, I wonder whether it makes sense to add the option to send logs also in the help menu, where it is for web.
