### ISSUE TITLE
Instrument metrics for Android for the IA project

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5013]
We want to know if the IA changes are successful. For this we need to learn more about how users currently use element and whether the IA changes are improving or not making worse their workflows.

Details of what needs to be instrumented are [in this internal spreadsheet](https://docs.google.com/spreadsheets/d/1ggIEyF2gYWjbCUiycPO2WwiK31gv_Cl7ShmdHP1JC1I/edit#gid=1483693159).
### Global search
- [x] Bounce rate from funnel: open search > visit room > open search (within time constraint)
        could be solved with userPath:
            - for group chat: `RoomDirectory` -> `RoomPreview` -> `RoomDirectory` 
            - for DMs `StartChat` -> `Room` -> `People/Home` -> `Start Chat`
 

- [x] Time and frequency to go from open search to tap result
       userPath: `RoomDirectory/StartChat` -> `Room/RoomPreview`
- [x] Frequency of open search and go back without tapping result
       userPath: `RoomDirectory/StartChat` ->  not `Room/RoomPreview`

Needs steps in Funnel (screen->event->screen)
- [x] Funnel for no progress from search results - guesstimate based on users that fell off search and how long did they stick around

User paths from Home, People, Rooms, etc:
- [x] From which tabs do users open global search
       separate events for searching people and rooms globally: `StartChat` and `RoomDirectory`

## Room header menu
User paths from RoomDetails:
- [x] When users tap on the room header, where do they go next?
       userPath: `Room` -> `RoomDetails`-> any of 'Room*' events
- [x] Add Home(create shortcut)
       Interaction(name: MobileRoomAddHome)
- [x] Leave
       Interaction(name: MobileRoomLeave)

## Left panel
User paths from SideBar:
- [x] Which menu items are users using in the left panel and how often?
       userPath: `SideBar` -> `SpaceMenu`, `Settings`,and other related screens
- [x] Do users switch spaces?
       `Interaction` event `SideMenuSwitchSpace `
- [x] How often do users tap on the selected space?
       `Interaction` event `SideMenuSelectedSpace `

## Settings
- [x] How often are people accessing their settings and what are they doing? (track screens for the moment)
       As discussed: userPath from `Settings`

## Spaces
- [x] Add a user property for how many spaces the user is in - to split users into cohorts
       user property `numSpace` still to be discussed which event we will use
- [x] Path to joining to space (were they invited, room directory, link, etc)
       event `JoinedRoom`. Taken out to https://github.com/vector-im/element-android/issues/5356
- [x] Number of times explore space is accessed and how (there is a screen for this - note that navigation from space to subscace is a second event)
      screen `SpaceExploreRooms `
- [x] Funnel from left panel to explore space
      userPath `SideBar` -> `SpaceExploreRooms`

## Rooms
- [x] Source of room open (did they click a link, did they search for the room, did they open it from one of the tabs? note that spaces look like rooms?)
     event `ViewRoom`. Taken out to https://github.com/vector-im/element-android/issues/5355
- [x] Path to joining to room (were they invited, room directory, link, etc)
     event `JoinedRoom`. Taken out to https://github.com/vector-im/element-android/issues/5356
- [x] Point of entry to create room dialog
     screen events `StartChat` and `CreateRoom`

**Comment by fedrunov** [comment]
Global Search:

- No screen name for RoomPreview 

Spaces

-SideBarEvent is not tracked before Explore Rooms
-number of spaces - how accurate should be?

Rooms

-CreateRoom is not tracked from Global Search and Space Manage screens
-When do we track ViewRoom
-Joined Room has many triggers

**Comment by fedrunov** [comment]
Rooms

| Screen | Use case | Trigger |
| ------------- | ------------- | ------------- |
| timeline | accept invite (DM?) + notification ? + upgrade retry  | - |
| message composer | slash command  | - |
| room list | accept invite  | - |
| invite accepter | auto accept invites  | - |
| room/space preview dialog | permalink, notification, etc* | - |
| notification | notification's accept button  | - |
| room preview screen | from global search  | - |
| room list item | by button in room item on global search  | - |
| space explore item | by button in room item on space explore  | - |

Spaces

| Screen | Use case | Trigger |
| ------------- | ------------- | ------------- |
| message composer | slash command  | - |
| space preview dialog | from permalink, notification, etc  | - |
| space directory | subspace  | - |
| space invite item | invite item in sidebar  | - |
| space preview screen | seems to be unused for now | - |

Preview Dialog issue:

for both Space and Room we have dialog with some information about it and "join button". This dialog is called from different places:
- click on invite notification (on notification itself, instead of "accept" button
- click on link in timeline
- open link from outside
- click on suggested room
- click on room in space explore

I suppose they should be split in a separate cases, if so, I'll add them to table above

**Comment by fedrunov** [comment]
There are places where user is navigated to room, so we should track ViewRoomEvent

| Screen | Use case | Trigger |
| ------------- | ------------- | ------------- |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |
| - | - | - |

**Comment by fedrunov** [comment]
| Screen | Use case | Trigger |
| ------------- | ------------- | ------------- |
| CreateDirectRoomActivity | after user creates a DM from users list | MessageUser |
| IncomingVerificationRequestHandler | verification request | Verification request |
| SearchFragment | navigate to event/message from search | MessageSearch |
| TimeLineFragmnet | handling a link in timeline | Timeline |
| PublicRoomsFragment | click on item in rooms global search | RoomDirectory |
| CreateRoomFragment | after room created | Created |
| RoomPreviewNoPreviewFragment | room preview | - |
| RoomJoinRuleActivity | switch to replacement room when user change join rules | - |
| IncomingShareFragment | share from outside the app | - |
| SpaceExploreActivity |  click on “open” button on room list item in a space explore | - |
| SpacePeopleActivity | click on a space member in space members list (from fab on space’s dm tab) | - |
| RoomListFragment | click on a room on Home screen | RoomList |

Also there is a bottom sheet with room preview from where user also can be navigated to Room, but this sheet is called in multiple places:

| Screen | Use case | Trigger |
| ------------- | ------------- | ------------- |
| HomeActivity | from parsed link  | - |
| SpaceExploreActivity | click on room in Space Explore | - |
| UserCodeActivity | on user code scanned | - |
| HomeActivity | from notification | - |
| Timeline | click on not joined room’s link | - |
| RoomList | on suggested room click | - |

**Comment by fedrunov** [comment]
map of room details items to analytics event

![Screenshot 2022-02-21 at 9 11 09](https://user-images.githubusercontent.com/66663241/154922641-e948b920-89df-47b7-b379-6357aad9e74b.png)

**Comment by fedrunov** [comment]
map of settings items to analytics event

![Screenshot 2022-02-21 at 10 04 32](https://user-images.githubusercontent.com/66663241/154922821-d0d3fc8f-7ac5-41fb-b7c7-09d35b390904.png)
s

**Comment by fedrunov** [comment]
- [ ] Room details screen tracked as `RoomSettings` instead of `RoomDetails`

**Comment by fedrunov** [comment]
Related PR - https://github.com/vector-im/element-android/pull/5257

changes tracking screen from tracking  when user leaves the screen to tracking when user enters the screen

**Comment by novocaine** [comment]
@niquewoodhouse added https://github.com/vector-im/element-meta/issues/208

**Comment by nadonomy** [comment]
> @nadonomy last week you suggested _not_ having the subspace functionality on mobile. I totally understand the reasons but I just want to check please what you're thinking of stopping:

My core motivation is to avoid us spending time on things which are either not very impactful or just not needed in the first place.

> * people making subspaces on mobile

We don't have any evidence users need to create or manage subspaces on mobile, so I don't think we should build this until we do, as it would require some effort to get right. Until we get more confidence I think we should consider pointing people to Web/Desktop to manage this.

> * people viewing a space by subspace on mobile

I don't think we should assume we need to display nested hierarchies when browsing Spaces on mobile.

Need to learn more (analytics!) but I would advocate for us to (1) ensure the rooms are always discoverable (2) display the subspace as secondary info until we gain more confidence in investing our time further.

@niquewoodhouse Does that help? I'm replying to your comment rather than internalising the scope of this entire issue, but can discuss further if helpful.

**Comment by niquewoodhouse** [comment]
> @niquewoodhouse Does that help? I'm replying to your comment rather than internalising the scope of this entire issue, but can discuss further if helpful.

Yes, thanks.
