### ISSUE TITLE
App crash on homeserver registration

### ISSUE THREAD

**Issue by yatadev** [vector-im/element-android#5218]
### Steps to reproduce

1. Where are you starting? What can you see?
- Try to register on my homeserver with registration tokens enabled
- A modal pops up, asking if i want to open the web client for registration
- The app crashes if i click yes

#### What did you expect?
Browser should open the homeserver url
#### What happened instead?
App crash

### Your phone model

Samsung galaxy s8+

### Operating system version

Android 9

### Application version and app store

Element v1.3.18, App Store

### Homeserver

Synapse v1.52.0

### Will you send logs?

No

**Comment by bmarty** [comment]
I can repro the crash by hacking the code (adding `!` at [this line](https://github.com/vector-im/element-android/blob/develop/vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthVariant.kt#L127)).

```
Caused by: java.lang.ClassCastException: im.vector.app.features.onboarding.OnboardingActivity cannot be cast to im.vector.app.features.signout.soft.SoftLogoutActivity
        at im.vector.app.features.signout.soft.SoftLogoutViewModel$Companion.initialState(SoftLogoutViewModel.kt:59)
```

Adding it to our milestone

**Comment by mnaturel** [comment]
Hi @ouchadam @bmarty , in order to find the best fix for that crash, I am wondering the purpose of the`SoftLogoutViewModel`. I see it is used in [FtueAuthWebFragment](https://github.com/vector-im/element-android/blob/f7aedff418cbec3a3f66c71b561a2b6e36d37699/vector/src/main/java/im/vector/app/features/onboarding/ftueauth/FtueAuthWebFragment.kt) and [LoginWebFragment](https://github.com/vector-im/element-android/blob/f7aedff418cbec3a3f66c71b561a2b6e36d37699/vector/src/main/java/im/vector/app/features/login/LoginWebFragment.kt) and [LoginWebFragment2](https://github.com/vector-im/element-android/blob/f7aedff418cbec3a3f66c71b561a2b6e36d37699/vector/src/main/java/im/vector/app/features/login2/LoginWebFragment2.kt).

I am asking the question because the `session` is injected into ViewModel meaning user should be authenticated, right? But for what I understand, it is used for sessionRecovery purpose which may indicating user is no more authenticated. And in the onboarding case I guess user will never be authenticated.

**Comment by mnaturel** [comment]
Okay thanks for explaining. The problem is that in `ActiveSessionHolder` the implementation of `getActiveSession()` is the following : 

```kotlin
fun getActiveSession(): Session {
    return activeSession.get()
            ?: throw IllegalStateException("You should authenticate before using this")
}
```

It means in the case of onboarding, injecting `Session` into `SoftLogoutViewModel` leads to a crash (not the same crash of this issue) since there is no active session when first instantiating the `FtueAuthWebFragment`. I don't know if we could have the same problem with the `LoginWebFragment`.
The solution I have for `FtueAuthWebFragment` is to remove the usage of this `SoftLogoutViewModel`, but I am not quite sure I can.
