### ISSUE TITLE
Wrong display name in search result for user

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5321]
### Steps to reproduce

Not sure how to reproduce:

![Screenshot_20220223-122439.png](https://user-images.githubusercontent.com/51663/155319750-c025e8aa-6160-455c-91c5-ae8673f9897f.png)

### Expected outcome

Danielle is called "Danielle"

### Application version and app store

1.4.0 / SDK 1.3.19 / olm 3.2.10

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by daniellekirkwood** [comment]
For context... I set my DisplayName to be Jano in the Threads P0 Delivery room (which @kittykat is a member of). My Display name is **only** changed in that room (using /myroomnick on web) and so I believe the correct behaviour here is to show my regular nickname/display name **not** the one that is specific only to the Threads P0 Delivery room

**Comment by kittykat** [comment]
I can confirm that I was trying to invite Danielle from an unrelated room in the Element space

**Comment by daniellekirkwood** [comment]
The behaviour of room-only display names should be such that it only applies _inside_ of that room. 

@bmarty do you have any background on this? Do you agree that the behaviour should be that we do not show room specific display names in the search results?

I'm testing on iOS now...

**Comment by ericdecanini** [comment]
I found this happening on the Desktop client
![image](https://user-images.githubusercontent.com/20701752/159715724-eff7aeea-e1f5-488c-8145-dd4f41498b45.png)

Are we sure it's not a backend issue?

**Comment by ericdecanini** [comment]
![image](https://user-images.githubusercontent.com/20701752/159764350-2400678a-3344-4a3e-9377-2049e206c808.png)

Fix is on the way, but I should also highlight that this bug in its entirety is that using `/myroomnick` currently changes your display name across the entire app. This affects not only your search result name, but also your name beside your avatar in the navigation drawer and such. 

This fortunately doesn't affect your display name in other rooms (existing or new), but another weird fact about this bug is that your display name will be set to whatever your display name is in the room you last sent a message in

**Comment by bmarty** [comment]
Fixed in 1.4.12
