### ISSUE TITLE
Iterate on badge / unread indicator color

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-android#5332]
I think there is a recent change in the color that introduced some weird colors in the badge (with value "130" in the screenshots below) and undead indicator (vertical bar on left)

|Light|Dark|
|-|-|
|<img width="483" alt="image" src="https://user-images.githubusercontent.com/3940906/155490792-65bae4b6-c10a-41d7-bf87-4a654f8cd97c.png">|<img width="483" alt="image" src="https://user-images.githubusercontent.com/3940906/155490738-2a99b13c-617b-4174-bd02-0144288978e5.png">|

In light theme it seems alright, but on dark, there is not enought contrast in the badge between text and background, and the vertical indicator color is maybe a bit too light.

@amshakal can you provide the Figma reference for a room list item in light and dark theme please?

New in release #5302

**Comment by amshakal** [comment]
Hello! [Here are the reworked colours](https://www.figma.com/file/8gIgD79bQoWdtfK3MtX59G/WTF-Moments?node-id=145%3A5236). Let me know what you think.

**Comment by bmarty** [comment]
We will use the ternary color. I will create a PR this morning

**Comment by bew** [comment]
Hello, like https://github.com/vector-im/element-android/pull/5456#issuecomment-1062907399, I still think the contrast is not enough with the dark 'after'  version in #5456..
It's hard to see at-a-glance which chat has the most unread, or how much is it.
For the light 'after'  version it even looks like there's less contrast than before 👀 is that intentional?
