### ISSUE TITLE
Create DM room only on first message

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-android#5525]
User Story

- As a user sending a DM to someone I do not have an active DM conversation with
- I want the room to be created only when I first send a message (text, image or voice)
- So that the recipient receives the invite only when there is a message in the room

Detail

- The user selects someone (Corey) to DM, the current implementation is : 
<img src="https://user-images.githubusercontent.com/8969772/157971649-4a62ab01-6380-4553-a130-7019f05a67f6.png" width="50%">

- [x] We request first to rename the option "CREATE" with "GO"
- [x] When the user presses 'GO': 
   - if there is already a DM with Corey : open the DM
   - if there isn't DM with Corey, instead of the room being created (and Corey being invited to an empty room), The user sees the following interface with the composer (the room has not been created).
<img width="243" alt="image" src="https://user-images.githubusercontent.com/8969772/157973680-87081c7b-f74b-4e2b-af6e-9673e892bba5.png">

- [x] If the user doesn’t send a message ( = Dismiss modal  (close button))  no room is created. The user has to start again.
- [x] If the user does send a message, then the DM room is created by inviting Corey and the message is sent.

Additional Requests

- [x] If several contacts have been selected in the picker before clicking on the GO option. The interface is adapted : 
<img width="239" alt="image" src="https://user-images.githubusercontent.com/8969772/157975054-f4ee2aac-33a9-4042-bbe1-8a639b0f03fb.png">

- [x] If the user selects at least one email address in the selected contact list, the resulting DM will be unencrypted. We have to hide the following tile in the interface
<img width="451" alt="image" src="https://user-images.githubusercontent.com/8969772/157976272-daa8eff2-5c7e-4d17-87d3-c9152fa1cadf.png">

**Comment by gaelledel** [comment]
- [ ] More space is needed next to the GO button (on the right) - security padding is mandatory on mobile min 12px
- [ ] Title in the fake room should read " Direct message" in singular
- [ ] We need a loading Screen between the screen when user sends the first message and when the room is created. The sting should read: "We're creating your room"
- [ ] If the invitee has not joined the room yet, we should hide the calling options in the nav. --> Gaelle to create Jira ticket 
- [ ] When inviting email address only the subsequent screen displays: " Empty Room" Instead of showing the full email address string to the user.
- [ ] When inviting email addresses + Matrix user, The email string is not recognised in the fake room meaning that: When choosing an email + a matrix ID > Next step shows only the Matrix ID and does not report the email address previously selected.
- When an invite is done by email and the person receiving the email creates an account in Element, we are then observing 3 members in the created room: the email address, the new element account, the sender account. This is NOT expected behaviour --> We should only show  2 members, the requester account and the newly created account.

**Comment by Florian14** [comment]
UX Review 14/09/22
- [ ] The keyboard should not overlap the timeline display

**Comment by giomfo** [comment]
I close this issue, each unchecked points (UX improvements and others) will be delivered later. They are all tracked by dedicated issues
