### ISSUE TITLE
Bring leaving space experience in line with iOS

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#5728]
#### What would you like to do?
Improve the leaving spaces user experience by bringing it into alignment with the [new iOS design](https://github.com/vector-im/element-ios/issues/4850#issuecomment-1087728561)

#### Why would you like to do it?
To have a simpler and smoother user experience.

#### How would you like to achieve it?
By simplifying the interaction to have only one step for selecting rooms.

### Additional context

Ideally we would continue to have a bottom sheet, but if that's not possible, then we can have a screen.

**Comment by fedrunov** [comment]
since there is no figma design, I've tried to adapt it to current android design @niquewoodhouse @amshakal please verify if it

Scrolled to top:
![Screenshot 2022-04-14 at 13 36 28](https://user-images.githubusercontent.com/66663241/163383367-b5ad69a6-539d-495a-b34a-d2e3e3a0eb0c.png)

Scrolled to bottom:
![Screenshot 2022-04-14 at 13 36 33](https://user-images.githubusercontent.com/66663241/163383370-faee3f59-c43d-4fa3-8bf5-599ad85057ed.png)

**Comment by kittykat** [comment]
Can we include the text about leaving the space please?

The the title should be:
> Leave <space name here>
> 
> Are you sure you want to leave <space name here>? Do you also want to leave all rooms and spaces in this space?

**Comment by fedrunov** [comment]
after discussion with @niquewoodhouse and @kittykat it was decided that this screen needs design revamp. Reassigned to Nique

**Comment by niquewoodhouse** [comment]
I'm blocking this behind the [iOS issue](https://github.com/vector-im/element-ios/issues/4850#issuecomment-1087728561), so when we have UI for that, I'll make the UI for this too

**Comment by niquewoodhouse** [comment]
We've altered the iOS design to 

- Remove the "select all" and "select none" options when someone is filtering
- Alter the "select rooms" header to just be "rooms"

For Android, I tried to find screens that have a fixed search and header, and found the "add existing rooms" to a space screen has this:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/1587166/164449384-b6e6e93b-f753-494b-a2cd-5dda48c5b8c3.png">



We could follow that, eg:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/1587166/164449417-51102a27-767b-4a3d-9ccf-cf7e857c95ea.png">

But I'd prefer to copy the tabs, with the filter top right

<img width="670" alt="image" src="https://user-images.githubusercontent.com/1587166/164449462-1afc4224-aae6-41d1-af45-c54d7efa4d49.png">

**Comment by fedrunov** [comment]
Looks good, I prefer option with filtering activated by button in toolbar, rather then visible always

**Comment by niquewoodhouse** [comment]
> Looks good, I prefer option with filtering activated by button in toolbar, rather then visible always

Lets do that and see how it goes.

**Comment by fedrunov** [comment]
@niquewoodhouse Some questions:

1. Buttons background

in a Figma design buttons are on a white background, so when list in a scrolled state it could look like this:


|Scrolled to top| Scrolled to bottom |
|-|-|
| ![image](https://user-images.githubusercontent.com/66663241/165105846-98ff4e0b-15eb-4593-bbb4-aecaa73724ce.png) | ![Screenshot 2022-04-25 at 16 08 23](https://user-images.githubusercontent.com/66663241/165106145-31a1a6eb-8fa6-4e79-b0c1-50841ed083f6.png)) |

Since panel with buttons have same background as list it "cuts off" items in a list

Same problem with toolbar, when user scrolls to top, but it's ok when user scrolls to bottom since toolbar gets elevation and shadow appears

2. Prompt text 

There is warning message in figma, but in current implementation (via dialog) this warning has some extras

"Are you sure you want to leave %s? "- general message and then **one** of following is added
"You are the only person here. If you leave, no one will be able to join in the future, including you." - added if you are the only member of space
"You\'re the only admin of this space. Leaving it will mean no one has control over it" - added if you are the only admin of space
"You won\'t be able to rejoin unless you are re-invited" - added if you are leaving private space

Shouldn't we implement same for this screen now?


3. Prompt text line break 

in Figma it looks like there is a line break after "Are you sure you want to leave <SpaceName>?", but it isn't added to the text in a Figma file. Without line break there could be "hanging" "If" like on screenshots above. But if we will put it there it could happen that last work of space name will "hang" on a separate line instead, depending on a screen size and user font settings. But I still think it's better to add a newline. What do you think?

Important note - don't look at toolbar's header and buttons, they are not finished :)

**Comment by niquewoodhouse** [comment]
I've taken a look at this issue in a bit more detail and tried to restrict changes to just content, to keep changes minimal.  

### Prompt text

To fit in all the messaging I needed to edit some content:
- remove the heading 
- edit the intro copy to introduce the relevant information and remove copy about the form below
- I changed the form title from `Rooms` to `Things in Space Name`
- Changed the two radio options to be `Leave all` and `Leave none` instead of `select all` and `select none` 

If only person: 

<img width="360" alt="Leave_2_only-person@2x" src="https://user-images.githubusercontent.com/1587166/165279658-64e0f13e-0f0b-48d2-b12e-959a759d57fd.png">

If only admin:

<img width="360" alt="Leave_2_only-admin@2x" src="https://user-images.githubusercontent.com/1587166/165279670-5135f6d8-0300-4f19-8afb-1eda1e12938b.png">

If re-invite would be needed:

<img width="360" alt="Leave_2_re-invite-needed@2x" src="https://user-images.githubusercontent.com/1587166/165279671-e5e814d9-6ee2-4625-a376-1574e4b31cb0.png">

Adding this content means we need another way to let people know how to use the form and I was wondering if we have a coach mark component that we can repurpose for this to appear the first time you use this form, like this:

<img width="360" alt="Leave_2_first-time@2x" src="https://user-images.githubusercontent.com/1587166/165279666-f7dcd026-cd8d-45f3-a660-710953fb2b82.png">

If we don't have anything like this, let me know, we can come up with alternatives.  I did consider having another step appear if one of these prompts is necessary but then the user is potentially tapping Leave 3x to actually leave, and it makes the leave button unpredictable as this may or may not appear.

____________

### On scroll

On the screenshots you've got quite a bit of content fixed at the top, I think it might be good to just let people have more space for the form, we don't need to keep so much fixed, like:

https://user-images.githubusercontent.com/1587166/165285952-cf33ba15-51b3-4aaf-85c7-2ce0205e71a3.mov

____________

### On buttons background

Where did you get the buttons from? Can we see if that component has a default background on it, or if its used elsewhere in the app?  I've tried looking in the app but the only place I can see two buttons side by side is Room > Room addresses >  Add local address
