### ISSUE TITLE
 Signin does not work on server with registration disabled

### ISSUE THREAD

**Issue by c3t4r4** [vector-im/element-android#5874]
### Steps to reproduce

1. When you log out and log in again, it doesn't work.
2. In version 1.4.11 it works normally, from version 1.4.12 and 1.4.13 it doesn't work.

### Your phone model

Xiaomi Poco F3

### Operating system version

Android 12

### Application version and app store

Element Version 1.4.12 and 1.4.13

### Homeserver

Sunapse Version 1.57.1

### Will you send logs?

No

**Comment by illspirit** [comment]
I'm having this issue too.

**Comment by eTomte** [comment]
This just happened to me as well, although I came by it another way, setting up a new user with an account that I had created manually.

As late as last week I was able to launch Element for the first time, select "Other" for my server, then under "connect to a custom server" I could enter the address for my homeserver, ie., https://matrix.xxxxxxx.org/.  at that point it would let me continue to the next screen where I could enter my username and password for that server.

Now, however, when I am on that screen I get an error message stating "Registration has been disabled" when I'm on the "Connect to a custom server" screen.

**Comment by 5HT2** [comment]
I came here to report this as well. Logs from synapse:

```bash
2022-05-01 15:59:26,923 - synapse.access.http.8008 - 427 - INFO - GET-5550 - [REDACTED] - 8008 - {None} Processed request: 0.000sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 558B 200 "GET /_matrix/client/versions HTTP/1.1" "Element/1.
4.13 (Linux; U; Android 12; Pixel 4 Build/SP2A.220405.00; Flavour GooglePlay; MatrixAndroidSdk2 1.4.13)" [0 dbevts]
2022-05-01 15:59:26,943 - synapse.access.http.8008 - 427 - INFO - GET-5551 - [REDACTED] - 8008 - {None} Processed request: 0.000sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 136B 200 "GET /_matrix/client/r0/login HTTP/1.1" "Element/1.
4.13 (Linux; U; Android 12; Pixel 4 Build/SP2A.220405.00; Flavour GooglePlay; MatrixAndroidSdk2 1.4.13)" [0 dbevts]
2022-05-01 15:59:27,274 - synapse.http.server - 95 - INFO - POST-5552 - <XForwardedForRequest at 0xffff872be7c0 method='POST' uri='/_matrix/client/r0/register' clientproto='HTTP/1.1' site='8008'> SynapseError: 403 - Registration has been disabled
2022-05-01 15:59:27,275 - synapse.access.http.8008 - 427 - INFO - POST-5552 - [REDACTED] - 8008 - {None} Processed request: 0.001sec/0.001sec (0.000sec, 0.000sec) (0.000sec/0.000sec/0) 66B 403 "POST /_matrix/client/r0/register HTTP/1.1" "Elemen
t/1.4.13 (Linux; U; Android 12; Pixel 4 Build/SP2A.220405.00; Flavour GooglePlay; MatrixAndroidSdk2 1.4.13)" [0 dbevts]
```

This does not happen with the desktop client.

**Comment by AshtenThePlatypus** [comment]
Can also confirm. I had to temporarily enable registration to get some people in.

**Comment by c3t4r4** [comment]
Removing v1.4.13 and installing v1.4.11 manually login works.

**Comment by subjugum** [comment]
Hi, I was wondering why people had issues with login. Turns out that the option to login is pushed out of view on lower resolution phones. Scrolling down on the selection screen will reveal the new login button. Apparently the other buttons are for registration only now, which is a weird thing to change.

![image](https://user-images.githubusercontent.com/1059909/166188780-f21329b6-4ac5-4b03-b526-1e8749116470.png)

**Comment by 5HT2** [comment]
> Instead what you're supposed to do is pick "other" on the screen shot posted, and enter in the address of the homeserver prior to this week doing that would let you progress to another screen where you could then log in. Now it fails with the registration related error. This a bug.

For what it's worth, the "other" option is what gives me the error when logging in, and "Sign in with Matrix ID" appears to work.

**Comment by Nateis1** [comment]
Hi. I can confirm that we have the same problem. Connection fails using the Other option and also with Matrix ID when you try to connect to your homeserver. When you uninstall the 1.4.13 release and install back the 1.4.11 one (using apk) you can connect back to your homeserver without any problem. Maybe a Register method launched instead of a SignIn one in the diff code between 1.4.11 an 1.4.12 release.

**Comment by 0spinboson** [comment]
also affected by this, have no way to log into my home server, as matrix ID option won't work either.

**Comment by alongls** [comment]
Hello
can confirm that we have the same problem,
downgrading the APP to V1.4.11 solved the issue

**Comment by rtest12** [comment]
I'm having this issue too.

**Comment by ouchadam** [comment]
am able to reproduce the issue on my side, working on a fix.

it's worth noting that `sign in with matrix id` will work if the homeserver has a .wellknown setup

**Comment by rtest12** [comment]
> it's worth noting that `sign in with matrix id` will work if the homeserver has a .wellknown setup

No, with .wellknown don't work too.

**Comment by ouchadam** [comment]
what's the error you're seeing with `sign in with matrix id` flow? I'll see if I'm able to reproduce, using my own homeserver I'm able to sign in without issue (with registration disabled) 

| REGISTRATION DISABLED | SIGN IN WITH ID |
| --- | --- |
|![Screenshot_20220504_132331](https://user-images.githubusercontent.com/1848238/166680649-44a02ee8-bec7-4fec-abda-9a6ec01a7332.png)|![after-matrixid-sign-in](https://user-images.githubusercontent.com/1848238/166680646-e69eeb65-3f91-4d77-8d53-50b16539426c.gif)

https://iswell.cool/.well-known/matrix/client

```
{"m.homeserver":{"base_url":"https://matrix.iswell.cool"}}
```

**Comment by 5HT2** [comment]
> it's worth noting that `sign in with matrix id` will work if the homeserver has a .wellknown setup

Ah, that explains why it was working for me and not other people.

**Comment by 0spinboson** [comment]
when I tried the matrix ID option it complained about invalid credentials, iirc.

**Comment by Toxblh** [comment]
@0spinboson confirm your case.

- If I tried login in https://app.element.io/ 
<img width="719" alt="image" src="https://user-images.githubusercontent.com/2198153/166986330-73cb2eed-3d00-4d26-aee3-6e084df8bcfc.png"> 
all good I can login. 

- If I tried use android login via custom server. I received "Registration has been disabled"

- If I tried via Matrix ID, and use my @user:domain. I received as expected "Unable to find a valid homeserver" because .well-known is disabled  

- If I tried via Matrix ID, and use my @user:domain:port. I received "Incorrect username and/or password"

**Comment by Toxblh** [comment]
Tested in 1.4.14 Confirm all works as expected via custom server

**Comment by ouchadam** [comment]
thanks for confirming!

**Comment by Nateis1** [comment]
Hi,
It does work correctly with 1.4.14 now. Thank you for your your help.
Kind Regards,
Mike.
