### ISSUE TITLE
Desynchronized 4S | Megolm backup causing Unusable backup

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-android#5906]
## Step to reproduce

1. **Web** | Create a new account on web
2. **Web** | Create a private room and send some E2EE messages
3. **Web** | Set up secure backup from Web
4. **Android** | Log this account on element android
5. **Android** | Verify the login using passphrase
6. **Android** | Go to Settings > Security & Privacy > Encypted Message Recovery
7. **Android** | Tap on Delete Backup
<img width="366" alt="image" src="https://user-images.githubusercontent.com/9841565/166420600-aed5b675-19c0-435c-891c-5cb15e55f8a9.png">
8. **Android** |  Create a new Backup with another passphrase
9. **Android** |  Logout the android session

10. **Android** | Login again on android
11. **Android** | Verify the login using passphrase

## Actual
Both your session can see a megolm backup but can't use it
<img width="594" alt="image" src="https://user-images.githubusercontent.com/9841565/166420786-1a6e9cb8-85e1-440b-87ce-4b41dd7e08e7.png">

=> Tap `Connect this session to Key Backup`: Entering the passphrase created in step `8` won't work (the one created on 3 neither)

## Expected 

You should be able to use backup.

## Root causes:

- EA lets you delete/create backups without updating the 4S https://github.com/vector-im/element-android/issues/1260
- EA is not signing the Megolm Backup with the MSK 
- Maybe we could do something when we detect that the key in 4S is incorrect? Like try the key to the backup directly and see if it works, then try to update the 4S?

**Comment by MadLittleMods** [comment]
Thanks for creating this issue @BillCarsonFr! This sounds so spot on to what I did and happy to see it's reproducible for you as well from a fresh state ❤ Impressed with your crypto knowledge and app interactions around it!

For reference, this spawning out of https://matrix.to/#/!HRPxYTDNTrjHtQknUy:matrix.org/$4PoOsVWDLWM_4Kd5OsWc52CASMgePmeDGRhgTtE9O2g?via=matrix.org&via=element.io&via=vector.modular.im which discusses my confusion around how to get my secure backup correct. It turned out to be corrupted in the way described in the issue 😫 and pretty much impossible to suss out what went wrong or how to fix it.

We also recorded session to discuss this which is available at https://www.youtube.com/watch?v=KSsOQZKfRPw but unfortunately the screen recording wasn't set to capture audio. The video is set to private as it has some sensitive information in it but if you want access, feel free to DM me on Matrix (Element employees only).


## Workaround and how to fix

If you get into this situation, you can fix it by using the **Settings** -> **Security & Privacy** -> **Encryption** -> **Reset** option in Element Web. This will create a new secure backup and set it as the new canonical source.

![](https://user-images.githubusercontent.com/558581/166505434-59233bc9-6b2e-4fd8-9f96-d0b5603674e7.png)


You can verify things went well and synced across devices by checking your `Backup version` under **Secure Backup** -> **Advanced** matches across them.

![](https://user-images.githubusercontent.com/558581/166505189-279a0ca8-883c-4609-9d68-832d83184fcd.png)


## Reference

The [*Demystifying Matrix Cryptography* talk by @BillCarsonFr](https://www.youtube.com/watch?v=QSeVHiN1dJE) also has some very good background information on how this all works and what the jargon all means.
