### ISSUE TITLE
Update F-Droid version to latest?

### ISSUE THREAD

**Issue by karolyi** [vector-im/element-android#6697]
### Your use case

Hey,

I see the version I use from F-Droid is 1 month behind the current. In there, it's 1.4.25 whereas 1.4.30 is already out with a couple other releases in between.

Why are the F-Droid releases so abandoned? If anything Element should float naturally towards those, instead of the very restrictive Play store.

### Have you considered any alternatives?

I don't have google services installed on my LineageOS.

### Additional context

Please pay more attention to truly freedom-minded store alternatives.

### Are you willing to provide a PR?

No

**Comment by genofire** [comment]
Element was not compatible to build by F-Droid:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11270


That was fixed in 1.4.28 which as not released, because it has other bugs:
https://github.com/vector-im/element-android/releases/tag/v1.4.28 - migration db

So track the checklist in #6669 , there should be F-Droid notified as next, to release.

**Comment by genofire** [comment]
@karolyi - released ... let's close this ticket?

**Comment by karolyi** [comment]
Yes, thank you, I have it now updated.

Please keep the future versions up-to-date on F-Droid too.
