### ISSUE TITLE
SSO Login has disappeared from the app, both Android and iOS

### ISSUE THREAD

**Issue by catalyst-eu** [vector-im/element-android#6827]
### Steps to reproduce

1. I load the app and give our company Matrix URL
2. There used to be a "login with SSO" in the app. In the browser it is still there, but the app doesn't have it.
3. As a result, I can no longer login to Matrix/Element

#### What did you expect?

A button "Login with SSO".

#### What happened instead?

The button is not there. There's only the option to login with username and password, but that doesn't work for us.

### Your phone model

Any Android phone

### Operating system version

Any android OS

### Application version and app store

1.4.32

### Homeserver

Synapse 1.4.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by hughns** [comment]
I've come across what I think might be the same issue in the OIDC Playground.

Test homeserver: https://synapse-oidc.lab.element.dev

Here is how it looks on app.element.io which is what I expect:
![image](https://user-images.githubusercontent.com/6955675/184558108-c2ce0ace-484c-4661-aa3c-df5408a4e19c.png)

On iOS the SSO button is missing:
![image](https://user-images.githubusercontent.com/6955675/184558154-a29cdb76-7ba9-4b18-8dec-fe11a1c0ed1c.png)

And on Android it is also missing:
![image](https://user-images.githubusercontent.com/6955675/184558277-778a5e1b-28af-4502-b8a2-38ef9277ed91.png)

The issue is triggered by having `https://synapse-oidc.lab.element.dev/_matrix/client/v3/login` returning `m.login.sso` but without the `identity_providers` value being set.

The [spec](https://spec.matrix.org/latest/client-server-api/#client-login-via-sso) says that `identity_provider` is optional.


I have a patch that fixes the behaviour on [Android](https://github.com/hughns/element-android/commit/d27fee5830a888576c5006ec89358c8038548d17):

![image](https://user-images.githubusercontent.com/6955675/184558593-14e09fd0-c161-4695-ba2b-b4bcb95fb81f.png)

I haven't found the appropriate place for iOS.
