### ISSUE TITLE
首次使用无法进入连接

### ISSUE THREAD

**Issue by mxhi** [vector-im/element-android#6828]
在中国首次使用设置服务器时需要VPN才能进入

**Comment by rebokdev** [comment]
I think that config server is just blocked in china
that's the problem

**Comment by mxhi** [comment]
> I think that config server is just blocked in china that's the problem

是这样的 ,中国屏蔽了matrix.org  . 也许可以调整一下 在初始界面点击 登录或者注册时 不要跟服务器通信,然后在输入登录或者注册信息确认时才与服务通信. 也许可以有更好的使用感受

**Comment by rebokdev** [comment]
matrix.org can't do anything with that because they aren't administrators of chinese internet
and chinese internet administrators had reason for blocking it

you can try searching other server that is no blocked

**Comment by xinzxie** [comment]
I also encountered the same problem. I cannot access the website matrix.org in China. I think that when I log in to my account for the first time, I should be able to enter a custom homeserver address instead of accessing matrix.org, because I cannot connect to matrix. org and cannot enter a custom homeserver address.

**Comment by xinzxie** [comment]
If we need to connect to matrix.org every time before jumping to the input custom homeserver address page, then we cannot use element in China, we hope to change the order of connecting to matrix.org and inputting custom homeserver address .
We need to enter the custom homeserver address directly, we need to enter the custom server address first, because China has firewall restrictions and cannot access matrix.org.
We need to be able to use element and custom homeserver also in China.

**Comment by xinzxie** [comment]
@rebokdev Can you pay attention to this issue? My English is very poor, I used google translate, hope you can understand what I wrote.

**Comment by fedrunov** [comment]
Thank you for taking the time to tell us about your issue.

I am going to close this issue as it has been resolved in 1.4.34. Feel free to reopen if it still persists
