### ISSUE TITLE
RiotX consumed 2Gb of data/day without being used

### ISSUE THREAD

**Issue by madduck** [vector-im/element-android#684]
I just found out that RiotX (0.8.0-dev) used 6.43Gb of mobile data in the last 3 days. However, I was not interacting with the app at all. Now all my data allowance is used up, and some additional costs were incurred, and I am quite annoyed by this.

What can I provide to help you get to the bottom of this?

![Screenshot_20191114-220810_Settings](https://user-images.githubusercontent.com/195073/68842627-84ba2000-072b-11ea-8b5e-6f3b2756b8f7.jpg)

**Comment by bmarty** [comment]
Hi @madduck 
We are sorry that this bug has a money impact for you.
We are investigating the issue.
Also, as an advice, I think you could add some data consumption setting to warn you when you reach a certain limit. (I've done it on mine, as a security net)

What is the RiotX version you are using?

Have you tried to send a big file (> 100Mo) to a room? We were facing this issue, and it has been fixed now.

Thanks
Benoit

**Comment by madduck** [comment]
Don't worry, it's not a big deal, but we ought to fix this. I am running 0.8.0-dev, and no, did not try to send a big file.

**Comment by dklimpel** [comment]
I have the same issue. Version 0.8.0-dev [157383069] (F-b1248)
I have disabled mobile data for RiotX.

**Comment by madduck** [comment]
This issue is a major adoption stopper for me. I'd love to be an early adopter, but with expensive mobile data in New Zealand, I cannot risk letting RiotX have access to 4G data. I'm often on the road, and need Riot then more than at the desk, which means I'm stuck with Riot-Android and it's feature freeze. :(

**Comment by ouchadam** [comment]
using newer versions of `Element Android` (1.3.7 & 1.3.8) on a small personal account and my element work account, I see relatively low bandwidth usage

| SMALL ACCOUNT (OCT) | SMALL ACCOUNT (NOV) |
| --- | --- |
![Screenshot_20211125_110137](https://user-images.githubusercontent.com/1848238/143429815-8b204301-2152-4e57-b81b-04247944966f.png)|![Screenshot_20211125_110146](https://user-images.githubusercontent.com/1848238/143429810-4d80d66e-2e12-446f-adb3-9a0411c29892.png)

| MEDIUM ACCOUNT (OCT) | MEDIUM ACCOUNT (NOV) |
| --- | --- |
|![Screenshot_20211125_110101](https://user-images.githubusercontent.com/1848238/143429821-6d036435-fc6b-4259-883b-a5fd20e3efae.png)|![Screenshot_20211125_110114](https://user-images.githubusercontent.com/1848238/143429818-24919825-04ec-4d10-9797-6d7d5f46eba2.png)


This issue was opened quite a while ago and on the previous RiotX app, as there have been no recent reports I'm going to close this, please feel free to reopen if `Element Android` experiences high bandwidth usage
