### ISSUE TITLE
Trailing whitespace for usernames not removed

### ISSUE THREAD

**Issue by sbg97** [vector-im/element-android#7111]
### Steps to reproduce

1. I made an account. Ex Username: "test" Password: "test"
2. Sign into the account with Username: "test " Password: "test"

Notice the trailing whitespace. This can be added automatically without the user noticing if you use autocorrect to complete your name.

#### What did you expect?

I would expect the trailing whitespace to be automatically removed before processing since I'm pretty sure usernames can't have trailing whitespace.

#### What happened instead?

I get a popup saying "Invalid username or password"

### Your phone model

moto g power

### Operating system version

Android 11

### Application version and app store

1.4.34 installed from F-Droid

### Homeserver

Synapse

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by mnaturel** [comment]
Thanks for raising the issue. I guess we should add a verification on the username field like we do on the signup screen to warn about invalid characters.

**Comment by ByeongsuPark** [comment]
Hi, I'd like to take this issue. 
Before that, I have a question about this issue's solution.
How about adding trim to the user's account input?
Considering that autocomplete is for the user's convenience, Adding a verification on the username's field as we do on the signup screen to warn about invalid characters leads to the user's inconvenience because it requires the user to do further action like deleting whitespace which is not needed if we just trim the user's input

**Comment by mnaturel** [comment]
> Hi, I'd like to take this issue. Before that, I have a question about this issue's solution. How about adding trim to the username input? Considering that autocomplete is for the user's convenience, Adding a verification on the username's field as we do on the signup screen to warn about invalid characters leads to the user's inconvenience because it requires the user to do further action like deleting whitespace which is not needed if we just trim the user's input

Hi @ByeongsuPark, adding a trim to remove any trailing whitespace is okay as solution. I think it should be done when pressing the signin button on app side. I guess we should also add it on SDK side so that every client benefits from this.

I have done some checks and it seems this trim was done in the previous version of the signin screen. Plus, I have also checked the [Matrix specs about userId](https://spec.matrix.org/v1.4/appendices/#user-identifiers) and whitespace is not allowed on any server so it should not block anyone from signin.
