### ISSUE TITLE
Deferred DMs - Locals are not deleted anymore within the new AppLayout

### ISSUE THREAD

**Issue by Florian14** [vector-im/element-android#7153]
### Steps to reproduce

First bug:
1. Start creating a DM with the start DM feature flag and the new App Layout enabled
2. Abort the DM creation and go back to the home list
3. Activate the recent rooms display from the AppLayout configuration
4. Then, the local room appears in the recent rooms

Second bug:
1. Start creating a DM with the start DM feature flag and the new App Layout enabled
2. Write some text without sending it
3. Abort the DM creation and go back to the home list
4. Start creating again a DM with the same person
4. Then, the local room is opened again with the drafted message

#### What did you expect?
The local room should not be persisted anymore when the user is back to the room list

### Will you send logs?

No

### Are you willing to provide a PR?

Yes

**Comment by daniellekirkwood** [comment]
This feels like good default behaviour (if the user is part way thru crafting a message, wants to switch rooms and then go back to that message, they are able to do so...) 

@giomfo as someone close to the behaviour of start a DM (and acting PM!) what do you think? :D

**Comment by giomfo** [comment]
> This feels like good default behaviour (if the user is part way thru crafting a message, wants to switch rooms and then go back to that message, they are able to do so...)

I agree the second "bug" described here looks like an expected behavior, but it was not planned in this first implementation. We decided to fix/remove it for the moment to prevent us from unstable behavior. 
We would have to work on this use case. FYI we already discussed about this point in Element-web repo [here](https://github.com/vector-im/element-web/issues/23196#issuecomment-1243751069). The plan would be to be able to rescue the pending message but keeping hidden the "local"(uncreated) room
