### ISSUE TITLE
Give the possiblity to configure the push gateway http url for airgapped deployments

### ISSUE THREAD

**Issue by gaelgatelement** [vector-im/element-android#7381]
#### What would you like to do?

I'd like to be able to configure the http push gateway. It's currently hardcoded and defaulted to [https://matrix.gateway.unifiedpush.org/_matrix/push/v1/notify](https://github.com/vector-im/element-android/blob/main/vector-config/src/main/res/values/config.xml#L24). 

#### Why would you like to do it?

When deploying Synapse/Element in an airgapped environment, I need to setup NTFY in this airgapped environment to enable push notifications. But at the moment, element cannot be configured to ask synapse to connect to this airgapped NTFY Push Gateway. Synapse tries to connect to the matrix.gateway.unifiedpush.org and gets a connection failure.

#### How would you like to achieve it?

 - A config in the well-known file on the homeserver would be perfect
 - A setting in element android would do the job but would be more of a hassle to configure on a large number of devices

### Are you willing to provide a PR?

No

**Comment by karmanyaahm** [comment]
Kind of an old issue, but this is not the case.

Element already works on an air-gapped network w/ ntfy since ntfy v1.26.0.

The hardcoded gateway is just a backup. Element prioritizes your self-hosted gateway.
https://github.com/vector-im/element-android/blob/a2f8fed63cc237081e699cd9046dc9c52bc88271/vector/src/main/java/im/vector/app/core/pushers/UnifiedPushHelper.kt#L105-L119

Only thing to keep in mind is Synapse needs HTTPS pushers, not HTTP. But that's a homeserver limitation, not Element. This issue should probably be closed, you can come to #unifiedpush:matrix.org for any questions.

**Comment by simaddis** [comment]
Is this for Android and iOS Element clients?

**Comment by mcg-android** [comment]
> The hardcoded gateway is just a backup. Element prioritizes your self-hosted gateway. https://github.com/vector-im/element-android/blob/a2f8fed63cc237081e699cd9046dc9c52bc88271/vector/src/main/java/im/vector/app/core/pushers/UnifiedPushHelper.kt#L105-L119

Can someone point a wannabe admin to the place where the address of the self-hosted gateway needs to be entered/stored/set so that Element-Android will see it and make use of it?

(Currently, matrix.gateway.unifiedpush.org has been unreachable for almost 24 hours; this dependency came as a bit of a surprise...)

**Comment by karmanyaahm** [comment]
> where the address of the self-hosted gateway needs to be entered/stored/set

It detects a gateway automatically if it's set up on your server, and depends on what push server you're using. Feel free to ask with more details in the Unifiedpush Matrix room.
