### ISSUE TITLE
Element does not seem to use custom user-installed CA

### ISSUE THREAD

**Issue by Vaelio** [vector-im/element-android#7398]
### Steps to reproduce

I have a proxy in my network that works for both HTTP and HTTPS (using custom CA)
I have installed the CA certificate into trusted CA store on android however once i connect to the network the application does not load and i see in the logs of my proxy that the client (Element) has droped the handshake because of the certificate not being to its taste.
The certificate looks good to me as it works both on PC and Android with my browsers.

Steps are:

1. Install custom CA certificate
2. Activate proxy in wireless settings
3. Connect to matching wifi
4. start Element

#### What did you expect?
I expected Element to load normally through the proxy

#### What happened instead?
Element refuses to load and, looking at the proxy's logs, drops the connection thinking the certificate is bad

### Your phone model

Oneplus 8 Pro

### Operating system version

Android 12

### Application version and app store

Tried both fdroid and gplay, but right now: 1.5.2 (olm 3.2.12) from gplay

### Homeserver

Synapse v1.69.0

### Will you send logs?

No

### Are you willing to provide a PR?

No

**Comment by jonnyandrew** [comment]
@Vaelio thanks for opening an issue. I think this is the expected behaviour for the app when built for release in the stores due to our [network security config](https://developer.android.com/training/articles/security-config).

You should however be able to inspect the network traffic using your proxy by installing a debuggable build of the app created in Android Studio. Please can you try this and if you are still experiencing this problem, please update your description with the steps you tried and add a comment with @jonnyandrew to let me know that it’s ready to be reopened.

**Comment by Vaelio** [comment]
@jonnyandrew Thanks, that answers my question. That means that if a company
wants to use Element but going through their proxy they must fork the
project right ? (Because i suppose debug builds are slower)

Le mar. 20 déc. 2022, 11:07, jonnyandrew ***@***.***> a
écrit :

**Comment by jonnyandrew** [comment]
It's not necessary to use a debug build but to make this work in a release build then yes, you would need to customise the network security configuration.
