### ISSUE TITLE
Two "Seen by" dots shown

### ISSUE THREAD

**Issue by rspears74** [vector-im/element-android#7882]
### Steps to reproduce

In the messages view, in a conversation with one person, I see two "Seen by" dots - one after my most recent message the other user has seen, and one after the last message they sent. Something like this (x represents the "Seen by" dot):
```
Me: hello
Them: How's it going?
                                     x
Me: Pretty good, you?
                                     x
Me: You there?
```

#### What did you expect?
I expect to see only one "Seen by" dot, after the most recent of my messages the other user has seen.

#### What happened instead?
I see two.

### Your phone model

Google Pixel 7

### Operating system version

Android 13

### Application version and app store

Element version 1.5.11

### Homeserver

non-public, synapse

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by bmarty** [comment]
I guess this is coming from the recent changes about read receipt for threads...

**Comment by alajovic** [comment]
Same problem noticed here.

Samsung Galaxy S22
Android 13
Element 1.5.11 from F-droid
matrix.org server

**Comment by Brendan-McDonnell** [comment]
I believe this is what @SpiritCroc was referring to here: https://github.com/vector-im/element-android/issues/6342#issuecomment-1354468759. They say they believe it is because of a read marker for both "null" and "main" threads causing issues.

I am also having issues with notifications on Android that started at the same time as the double read markers appeared. Possibly not notifying because it's wrongly considered read?

**Comment by Eriatolc** [comment]
Probably the same issue here, but the two "Seen by" dots (of the same person) can be at the same place.

Oxygen OS 12 on OnePlus Nord 2T, but add the same issue some weeks ago on my previous OnePlus Nord.
Element 1.5.11 from Play Store.

![Screenshot_2023-01-06-07-44-33-25_759d22c01f61b30a3a2e41e7176310a8](https://user-images.githubusercontent.com/1306234/210962975-65572941-f317-40cb-af26-3f343c0dc544.jpg)

**Comment by SpiritCroc** [comment]
> Probably the same issue here, but the two "Seen by" dots (of the same person) can be at the same place.

From my experience, it only looks like this due to to reactions. When enabling showing hidden events in the developer options, one receipt is usually on the message itself, and another on the reaction.

**Comment by Brendan-McDonnell** [comment]
> > Probably the same issue here, but the two "Seen by" dots (of the same person) can be at the same place.
> 
> From my experience, it only looks like this due to to reactions. When enabling showing hidden events in the developer options, one receipt is usually on the message itself, and another on the reaction.

This does not align with my experience. I've been having this issue for weeks and have not personally observed any interactions with reactions

**Comment by Brendan-McDonnell** [comment]
Did a quick test. It obviously isn't complete. Here's how it went:

In this case, what I was seeing was a *delayed* bubble. Sometimes, I see that it appears my message is read immediately when I don't believe it has, which is rather the inverse of the behavior I saw in this test. One possible difference is that I had a Windows desktop client open at the same time to compare the placement of read bubbles.
![1](https://user-images.githubusercontent.com/36059032/211438976-245dbc28-2d06-4aac-be44-5b9620b53b60.png)

The delayed bubble sometimes got stuck on a single message for multiple events and sometimes updated. I'm not sure of the pattern between the two. For example, between these two states the delayed bubble stayed on the same message despite many messages from both of us between.
![3](https://user-images.githubusercontent.com/36059032/211439267-e151e6fc-24ec-4624-a250-47393c531a10.png)
![4](https://user-images.githubusercontent.com/36059032/211439387-0c4e8793-e847-49bc-9d33-a879d1fdbbe3.png)

Both read bubbles then jumped on their next message:
![5](https://user-images.githubusercontent.com/36059032/211439713-1da8f128-9e26-4a4c-a1d4-bbd0904c47d5.png)

I do also see that one read bubble can be on a reaction, but I would guess this is expected behavior?
![8](https://user-images.githubusercontent.com/36059032/211439834-ad3e0985-6fe0-406c-a50e-cf1d24b83234.png)

As an aside, here is what they see, which appears to be the same behavior to me:
![extra](https://user-images.githubusercontent.com/36059032/211439902-82902288-8e67-479c-a0cd-cd1cbcea98e6.png)
(some messages with unverified session but they say this is typical even when not using that).

**Comment by Brendan-McDonnell** [comment]
On notifications: I simply don't receive them most the time since this behavior began (Google Pixel 5, up-to-date Android, installed from F-Droid). They get vibration for one second with the notification showing briefly before vanishing (Google Pixel 7, up-to-date Android, installed from Play Store). Not sure if this issue is related or if it is a separate problem that started around the same time.

**Comment by rspears74** [comment]
> They get vibration for one second with the notification showing briefly before vanishing (Google Pixel 7, up-to-date Android, installed from Play Store).
I seem to get this behavior sometimes too, but not all the time(?) - I'm also Google Pixel 7, current Android, Play Store.

**Comment by SpiritCroc** [comment]
> > > Probably the same issue here, but the two "Seen by" dots (of the same person) can be at the same place.
> > 
> > 
> > From my experience, it only looks like this due to to reactions. When enabling showing hidden events in the developer options, one receipt is usually on the message itself, and another on the reaction.
> 
> This does not align with my experience. I've been having this issue for weeks and have not personally observed any interactions with reactions

Note I'm not saying duplicate read receipts are related to reactions. My point is that whenever it looks like duplicated read receipts are attached to the same message, that's usually just because the receipts are "flattened" when there are reactions, and once you have hidden events enabled, the receipts still attach to different events.

**Comment by bmarty** [comment]
Investigating this issue.

Confirming the `main` and `null` issue on read receipt by inspecting the database of benoit10518 account, on a room without any thread:

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/3940906/211581087-757ce99b-b48a-4f45-98f0-1fc05d609da7.png">

Event `$cIf...` is the latest event of the room, and Event `$aOg...` is the latest event sent by benoit10518.

But there I do not see the issue on the device.

I guess when sending an Event to a room we add a RR to the database, but not using `main` and this is causing the issue. Still digging.

**Comment by Brendan-McDonnell** [comment]
Poked around in some blames. I'm guessing the issue can be tracked down to #7474. Matches the timeline and I don't see more recent changes on thread ids' interactions with read receipts since. Lots of null checking going on because `threadId` can be null, so my first guess would be some logic error there.

It could also be an issue with migrating the database #7640? Maybe a `ReadReceiptEntity` is getting the wrong `threadId` (`null` or `main`) when it shouldn't, leading to a duplicate?

If this is not a ubiquitous issue, I would guess some edge case happened to a subset of users. Some uncommon logic state, or the migration not properly handling a certain type of events, that sort of thing.

**Comment by SpiritCroc** [comment]
FWIW, I've seen the same chat head placement for the same chat across multiple devices on multiple Elements/Element-based clients since the threads update, and it persists across initial syncs. So it seems 100% deterministic from my experiments / if I haven't missed any case.

**Comment by Brendan-McDonnell** [comment]
> Investigating this issue.
> 
> Confirming the `main` and `null` issue on read receipt by inspecting the database of benoit10518 account, on a room without any thread:
> 
> <img alt="image" width="1416" src="https://user-images.githubusercontent.com/3940906/211581087-757ce99b-b48a-4f45-98f0-1fc05d609da7.png">
> 
> Event `$cIf...` is the latest event of the room, and Event `$aOg...` is the latest event sent by benoit10518.
> 
> But there I do not see the issue on the device.
> 
> I guess when sending an Event to a room we add a RR to the database, but not using `main` and this is causing the issue. Still digging.

I'd be happy to take a look at the data for the room I'm experiencing this issue in.

I'm not an Android dev — is the best approach setting up an emulator through Android Studio, logging into my account, and using Flipper per [flipper.md](https://github.com/vector-im/element-android/blob/3dcec85dea47feb823cc8dcc03cf7871af91be45/docs/flipper.md)?

**Comment by bmarty** [comment]
> I'm not an Android dev — is the best approach setting up an emulator through Android Studio, logging into my account, and using Flipper per [flipper.md](https://github.com/vector-im/element-android/blob/3dcec85dea47feb823cc8dcc03cf7871af91be45/docs/flipper.md)?

Yes. The main issue is that you will not be able to query the database with Flipper. So if there are lots of entries, it can be painful to inspect.

**Comment by Brendan-McDonnell** [comment]
Okay, here are my results. I had forgotten how much of a pain android development was to get set up the first time.

Not sure what all needs to be censored so I was liberal with it. Note that on the database photos, my friend is censored in pink to distinguish the different `userId`s

## Test
### State A
![screencap-A](https://user-images.githubusercontent.com/36059032/211733205-8055081f-1495-46a1-8c02-b866b909e9bf.png)
![database-A](https://user-images.githubusercontent.com/36059032/211733217-74054fdb-8913-4d29-9a76-f32d7e6e1344.png)

### State B
![screencap-B](https://user-images.githubusercontent.com/36059032/211733364-d1a76639-1804-4914-afd2-91af9bf172e4.png)
(unfortunately, I did not have it 😞)
![database-B](https://user-images.githubusercontent.com/36059032/211733370-eacced4d-01ac-4b17-ae2d-dfd02621a69b.png)

### State C
![screencap-C](https://user-images.githubusercontent.com/36059032/211733397-262112f6-87c7-41f9-a342-a2f7dc4cbcf7.png)
![database-C](https://user-images.githubusercontent.com/36059032/211733409-96c6b216-084a-493a-85cd-52f806a5a390.png)

### Friend's perspective
I had my friend send a screenshot at the end. They said that my second read receipt was also on the `$went...` message the whole time.
![screencap-friend](https://user-images.githubusercontent.com/36059032/211739290-a297cb8f-c016-43fa-9b28-71c0acfcaaa2.png)

### `eventId` / message reference table
```
| eventId  | message content      | state(s) |
|----------|----------------------|----------|
| $went... | Seen 14 50           | A,B,C    |
| $0czA... | sample message       | A        |
| $IcDf... | That the issue in... | B        |
| $OhAJ... | Okay, I need you...  | C        |
```

## Insights
Two things I observed here: first, for this test, both my and my friend's second read receipt were on the same `$went...` message. It would be worth checking further to see if they're always in sync.

Second, compared to the [previous test](https://github.com/vector-im/element-android/issues/7882#issuecomment-1377390326) @bmarty ran, there's one more read receipt. The previous test had one single `null` from the recipient and a `null` and `main` from the account owner, if I understand correctly. My test had full symmetry. The discrepancy might be because the previous test didn't have multiple events made and seen by both accounts beforehand, but if it did, that might be our problem.

**Comment by sociedadXD** [comment]
For me there is one read receipt which is real which shows up when the user has actually seen the message, and then there is a fake read receipt that shows up instantly whenever a message is sent. When the user has actually seen the most recent message, then both read receipts will be on that message, when he hasn't there will be the fake read receipt on the most recent message and the real one somewhere above on the last message he actually saw. And this is only visible on android. On element desktop, I can only see the fake read receipt from android users, so it is impossible to tell if they actually saw the message or not.

**Comment by RayBB** [comment]
I am still seeing this pretty much daily on the latest version of the app.

**Comment by borisrunakov** [comment]
Never stopped for me on all versions since reported.

**Comment by dav23r** [comment]
Like others said, still affects my experience. Would be happy to provide any logs/debug information per request.

**Comment by TheEagleByte** [comment]
This is showing up a lot for our users. Will often show them along side each other as if multiple people viewed up to that message, but upon looking at the icons and opening it up, they're from the same person. Image below:

![image](https://user-images.githubusercontent.com/28986398/227556527-20651c91-69db-4f87-b42f-12f560d6b288.png)

**Comment by olmari** [comment]
Also +1 from here. While not mos urgent thing, most irritating it is.
