### ISSUE TITLE
Ping to posthog.hss.element.io ??

### ISSUE THREAD

**Issue by skdubg** [vector-im/element-android#8020]
Hi,

why does the App with Version 1.5.18 initiate an ping request to posthog.hss.element.io after start of phone or app?

What is the reason?
Which data is transfered?

Please explain it.
Thanks

**Comment by notramo** [comment]
The project uses Posthog for analytics. The data sent can be examined from the source code.

**Comment by ara4n** [comment]
The app should never talk to posthog unless the user has explicitly opted into analytics. If it is, then it’s a stupid bug that should be fixed.

**Comment by ara4n** [comment]
context: https://social.tchncs.de/@kuketzblog/109761960447612852

**Comment by ara4n** [comment]
This was an innocent bug - it turns out that the posthog library will still ping the `<server>/decide/?v=2` endpoint on the server if you call `posthog.identify()`, even if you have explicitly opted out of analytics via `posthog.optOut(true)`.  We've fixed that in https://github.com/vector-im/element-android/pull/8031, which should be in today's release (Element Android 1.5.22). Thanks to @skdubg and Mike Kuketz for bringing it to our attention.

**Comment by bmarty** [comment]
Fix will be available in Element 1.5.24.

**Comment by nach0** [comment]
I just updated to version 1.5.25 and Element is still trying to connect to posthog. I opted out of "send analytics data"

**Comment by nach0** [comment]
I am on version 1.5.26 and Element still tries to connect to posthog.HSS.element.io even when I opted out of analytics. 
Wasn't this supposed to be fixed in 1.5.24?

**Comment by bmarty** [comment]
> I am on version 1.5.26 and Element still tries to connect to posthog.HSS.element.io even when I opted out of analytics. Wasn't this supposed to be fixed in 1.5.24?

Yes this was suppose to be fixed. I have check and the fix is still there.

But... I can see that `reloadFeatureFlagsRequest` is still doing this request... I do not know if one day we decide to use Posthog feature flag feature (I think they are using this on Element iOS), but this is not strictly related to the analytics...

In the mean time, I can provide a fix to ensure that no request is done when analytics is opt-out, with the side effect that Posthog feature flags will be unavailable.

**Comment by Johennes** [comment]
Thanks for looking into this @bmarty. 🙏 I don't currently see _any_ feature flags configured in our PostHog instance. So while this seems like a potentially useful feature in the future, I'd say it's fine to disable for now.

**Comment by drupol** [comment]
Hi,

This issue should be reopened. I'm using version 1.5.32 and my pi-hole is still blocking requests to `posthog.hss.element.io`.

![image](https://github.com/vector-im/element-android/assets/252042/e5c44c21-9fed-47a1-a8ac-b461aaa47049)
