### ISSUE TITLE
Remove MapBox Tracker from F-Droid Android App

### ISSUE THREAD

**Issue by marek22k** [vector-im/element-android#8300]
### Steps to reproduce

Install element from F-Droid, use a tracker scanner like Warden.
![Screenshot_20230403-162225_1](https://user-images.githubusercontent.com/46723399/229538618-7e0c6503-7f76-42c1-b2dd-59b8d1308973.png)

#### What did you expect?
No trackers

#### What happened instead?
MapBox Tracker

### Your phone model

FP4

### Operating system version

CalyxOS 4.7.5 Android 13

### Application version and app store

1.5.28 F-Droid

**Comment by Johennes** [comment]
German forum post from the Threema community about the same issue in their app: https://threema-forum.de/index.php?thread/7215-logger-und-tracker-der-threema-app/

Looks like it can be turned off with an SDK setting: https://github.com/threema-ch/threema-android/blob/29816f75fbbce6b6491ddd13366772d9f8ae9c55/app/src/main/java/ch/threema/app/ThreemaApplication.java#L974-L979

**Comment by julioromano** [comment]
It seems a false positive, Warden will trigger that warning whenever it sees `com.mapbox.mapboxsdk` in an app's classpath.
The Warden check is here: https://gitlab.com/AuroraOSS/AppWarden/-/blob/master/app/src/main/assets/trackers.json#L1460

Thing is we don't use MapBox in Element Android. We use [MapLibre](https://maplibre.org/) which is a fork of MapBox which, among other things, removes the telemetry code.
MapLibre still uses the same package names from MapBox so Warden will trigger a warning because that classpath is actually there. But there's actually no telemetry in the source.

**Comment by marek22k** [comment]
Thanks for the answer!

**Comment by julioromano** [comment]
Filed this to report the false positive: https://gitlab.com/AuroraOSS/AppWarden/-/issues/25
