### ISSUE TITLE
Element Android 1.5.* no run in background option and calling notification not working when app closed

### ISSUE THREAD

**Issue by unknown1818** [vector-im/element-android#8397]
### Steps to reproduce

Run Element Android app and look in settings for option in background.
Do i need google play this to working? or download app from store not direct apk?

### Outcome

Run Element Android app in background when app is closed to get live notification

### Your phone model

Samsung S10

### Homeserver

Synapse

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by Florian14** [comment]
Hi @unknown1818, installing direct apk from the github page or build by yourself should be fine.
Can you give us more details about the version you've installed? (`Settings -> Help & about -> version`)
Do you have the play services on your device?
Could you run the troubleshooting test from `Settings -> Notifications -> Troubleshoot Notifications` and share the result here?

**Comment by unknown1818** [comment]
thank you for your time, version 1.5.32 latest from github direct download, i have disabled google play

**Comment by unknown1818** [comment]
ok i found the problem was a google play version doesent have this option to run in background only fdroid have

**Comment by Florian14** [comment]
> Hi @Florian14 thank you for your time, version 1.5.32 latest from github direct download, i have disabled google play
> 
> notification tests all passed, only when app is closed everything is gone
> 
> i got element on 3 android devices s10 and i cant make a call status is offline after some time all apps are not working in background even on phone with google play service
> 
> where is this option to run in background? homeassistant have nice option with icon in tray always connection

Thanks for the update. The notifications should work in background on devices with play services enabled and a GPlay version of the app. In that case, we're using the push notifications from Firebase to wake up the phone. Otherwise, you can use another push provider (search for `unified push` to see how to setup this).

The background notifications in the fdroid version are a bit different, it's using the pull notification, ie. the device will request the server for notifications at regular intervals (30 sec by default if I remember correctly but you can change this value). You should also know that it will affect the battery consumption.
