### ISSUE TITLE
Filter bar instead of bottom tabs

### ISSUE THREAD

**Issue by frandavid100** [vector-im/element-android#962]
Riotx's bottom tabs feel kind of awkward, because:

1. They force you to choose between seeing direct conversations and seeing rooms, even though there's no big difference between them.

2. Direct conversations / rooms is just one of many factors that could be used instead, such as read / unread / notified, favorites / normal priority / low priority, custom tags, and so on.

I think a filter bar (like the one used in the Google Play Books app) would be much better at letting the user filter according to any of these factors, and get in the way much less. Here is a mockup of what it could look like:

<img src="https://user-images.githubusercontent.com/694794/73837093-fed0e100-4810-11ea-840a-727525741f2c.png" width="50%">

**Comment by steef435** [comment]
While I'm not sure the above mockup is the best option, I do agree with the general awkwardness of the tabs currently. The way I ended up using them:
- I basically never use the home tab
- I tag the most interesting/smaller rooms (even with multiple people) as "direct message"
- I tag the less interesting/larger rooms as "rooms"
- Then there are additionally the other tags for further sorting

So I basically already use the bottom bar as a sort of tag bar proposed here.

**Comment by frandavid100** [comment]
Yes, that's been basically my experience too.

**Comment by bmarty** [comment]
FWIW I mainly use the room filter, which mixes DM and rooms, and also the breadcrumbs panel, which also mixes all sort of rooms...
That said, the home tab is not the final version.

**Comment by weeman1337** [comment]
It is a bit confusing finding my messages. I have to check the direct messages and rooms tab.  
So in my opinion merging these two views improves the usability (for me).

The filter idea is okay to cover "power users". I just want to have a single list containing my chats.

**Comment by daniellekirkwood** [comment]
Hey there! Thanks for the suggestion - we're a few weeks away from releasing a redesign of the app in which users will be able to introduce 'filters' to their home screen instead of seeing tabs. 

I'm assigning this issue to myself as it will be closed when we release the new version of the app. 

We hope you like the changes!

**Comment by frandavid100** [comment]
Hey, Danielle. I've been using the new layout for some days, and I think it's a big improvement over the old one. Can't wait for it to hit all users.

I was wondering if you ever explored the top filter bar idea, and in that case, what made you go for the spaces-button-at-the-bottom approach instead. Cheers!

**Comment by daniellekirkwood** [comment]
We did explore the filter button style (in your image) as well as tabs (where we landed). 
	During our research we learned that the desired order of these filters and the number of them was different for all users. We're not yet ready to offer a level of personalisation for these items and so chose the Tabs style as our approach for now. However, as we roll this out and learn more we may iterate. 

As for Spaces in the bottom: Spaces are a way to group rooms and chats, not filter rooms and chats therefore we did not want to add switching space into the filters at the top of the screen; We needed to find a spot for space switching that was within easy reach but did not take up too much room. We also knew that in order to see and switch spaces and sub-spaces we needed to provide a bottom sheet - when we tested with space switching at the top of the screen, the bottom sheet felt really 'off'.

Hope this helps.
